// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

/**
 * Protobuf type {@code com.gomokumaster.proto.BoardRow}
 */
public  final class BoardRow extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gomokumaster.proto.BoardRow)
    BoardRowOrBuilder {
  // Use BoardRow.newBuilder() to construct.
  private BoardRow(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BoardRow() {
    pieces_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private BoardRow(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              pieces_ = new java.util.ArrayList<com.gomokumaster.proto.Piece>();
              mutable_bitField0_ |= 0x00000001;
            }
            pieces_.add(
                input.readMessage(com.gomokumaster.proto.Piece.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        pieces_ = java.util.Collections.unmodifiableList(pieces_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_BoardRow_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_BoardRow_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gomokumaster.proto.BoardRow.class, com.gomokumaster.proto.BoardRow.Builder.class);
  }

  public static final int PIECES_FIELD_NUMBER = 1;
  private java.util.List<com.gomokumaster.proto.Piece> pieces_;
  /**
   * <pre>
   *可以理解为List&lt;Piece&gt;
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
   */
  public java.util.List<com.gomokumaster.proto.Piece> getPiecesList() {
    return pieces_;
  }
  /**
   * <pre>
   *可以理解为List&lt;Piece&gt;
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
   */
  public java.util.List<? extends com.gomokumaster.proto.PieceOrBuilder> 
      getPiecesOrBuilderList() {
    return pieces_;
  }
  /**
   * <pre>
   *可以理解为List&lt;Piece&gt;
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
   */
  public int getPiecesCount() {
    return pieces_.size();
  }
  /**
   * <pre>
   *可以理解为List&lt;Piece&gt;
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
   */
  public com.gomokumaster.proto.Piece getPieces(int index) {
    return pieces_.get(index);
  }
  /**
   * <pre>
   *可以理解为List&lt;Piece&gt;
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
   */
  public com.gomokumaster.proto.PieceOrBuilder getPiecesOrBuilder(
      int index) {
    return pieces_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < pieces_.size(); i++) {
      output.writeMessage(1, pieces_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < pieces_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, pieces_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gomokumaster.proto.BoardRow)) {
      return super.equals(obj);
    }
    com.gomokumaster.proto.BoardRow other = (com.gomokumaster.proto.BoardRow) obj;

    boolean result = true;
    result = result && getPiecesList()
        .equals(other.getPiecesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPiecesCount() > 0) {
      hash = (37 * hash) + PIECES_FIELD_NUMBER;
      hash = (53 * hash) + getPiecesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gomokumaster.proto.BoardRow parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gomokumaster.proto.BoardRow parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gomokumaster.proto.BoardRow parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gomokumaster.proto.BoardRow parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gomokumaster.proto.BoardRow parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.BoardRow parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gomokumaster.proto.BoardRow parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.BoardRow parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gomokumaster.proto.BoardRow parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.BoardRow parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gomokumaster.proto.BoardRow prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gomokumaster.proto.BoardRow}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gomokumaster.proto.BoardRow)
      com.gomokumaster.proto.BoardRowOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_BoardRow_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_BoardRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gomokumaster.proto.BoardRow.class, com.gomokumaster.proto.BoardRow.Builder.class);
    }

    // Construct using com.gomokumaster.proto.BoardRow.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPiecesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (piecesBuilder_ == null) {
        pieces_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        piecesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_BoardRow_descriptor;
    }

    public com.gomokumaster.proto.BoardRow getDefaultInstanceForType() {
      return com.gomokumaster.proto.BoardRow.getDefaultInstance();
    }

    public com.gomokumaster.proto.BoardRow build() {
      com.gomokumaster.proto.BoardRow result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.gomokumaster.proto.BoardRow buildPartial() {
      com.gomokumaster.proto.BoardRow result = new com.gomokumaster.proto.BoardRow(this);
      int from_bitField0_ = bitField0_;
      if (piecesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          pieces_ = java.util.Collections.unmodifiableList(pieces_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.pieces_ = pieces_;
      } else {
        result.pieces_ = piecesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gomokumaster.proto.BoardRow) {
        return mergeFrom((com.gomokumaster.proto.BoardRow)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gomokumaster.proto.BoardRow other) {
      if (other == com.gomokumaster.proto.BoardRow.getDefaultInstance()) return this;
      if (piecesBuilder_ == null) {
        if (!other.pieces_.isEmpty()) {
          if (pieces_.isEmpty()) {
            pieces_ = other.pieces_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePiecesIsMutable();
            pieces_.addAll(other.pieces_);
          }
          onChanged();
        }
      } else {
        if (!other.pieces_.isEmpty()) {
          if (piecesBuilder_.isEmpty()) {
            piecesBuilder_.dispose();
            piecesBuilder_ = null;
            pieces_ = other.pieces_;
            bitField0_ = (bitField0_ & ~0x00000001);
            piecesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPiecesFieldBuilder() : null;
          } else {
            piecesBuilder_.addAllMessages(other.pieces_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gomokumaster.proto.BoardRow parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gomokumaster.proto.BoardRow) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.gomokumaster.proto.Piece> pieces_ =
      java.util.Collections.emptyList();
    private void ensurePiecesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        pieces_ = new java.util.ArrayList<com.gomokumaster.proto.Piece>(pieces_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gomokumaster.proto.Piece, com.gomokumaster.proto.Piece.Builder, com.gomokumaster.proto.PieceOrBuilder> piecesBuilder_;

    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public java.util.List<com.gomokumaster.proto.Piece> getPiecesList() {
      if (piecesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pieces_);
      } else {
        return piecesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public int getPiecesCount() {
      if (piecesBuilder_ == null) {
        return pieces_.size();
      } else {
        return piecesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public com.gomokumaster.proto.Piece getPieces(int index) {
      if (piecesBuilder_ == null) {
        return pieces_.get(index);
      } else {
        return piecesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public Builder setPieces(
        int index, com.gomokumaster.proto.Piece value) {
      if (piecesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePiecesIsMutable();
        pieces_.set(index, value);
        onChanged();
      } else {
        piecesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public Builder setPieces(
        int index, com.gomokumaster.proto.Piece.Builder builderForValue) {
      if (piecesBuilder_ == null) {
        ensurePiecesIsMutable();
        pieces_.set(index, builderForValue.build());
        onChanged();
      } else {
        piecesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public Builder addPieces(com.gomokumaster.proto.Piece value) {
      if (piecesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePiecesIsMutable();
        pieces_.add(value);
        onChanged();
      } else {
        piecesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public Builder addPieces(
        int index, com.gomokumaster.proto.Piece value) {
      if (piecesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePiecesIsMutable();
        pieces_.add(index, value);
        onChanged();
      } else {
        piecesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public Builder addPieces(
        com.gomokumaster.proto.Piece.Builder builderForValue) {
      if (piecesBuilder_ == null) {
        ensurePiecesIsMutable();
        pieces_.add(builderForValue.build());
        onChanged();
      } else {
        piecesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public Builder addPieces(
        int index, com.gomokumaster.proto.Piece.Builder builderForValue) {
      if (piecesBuilder_ == null) {
        ensurePiecesIsMutable();
        pieces_.add(index, builderForValue.build());
        onChanged();
      } else {
        piecesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public Builder addAllPieces(
        java.lang.Iterable<? extends com.gomokumaster.proto.Piece> values) {
      if (piecesBuilder_ == null) {
        ensurePiecesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pieces_);
        onChanged();
      } else {
        piecesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public Builder clearPieces() {
      if (piecesBuilder_ == null) {
        pieces_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        piecesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public Builder removePieces(int index) {
      if (piecesBuilder_ == null) {
        ensurePiecesIsMutable();
        pieces_.remove(index);
        onChanged();
      } else {
        piecesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public com.gomokumaster.proto.Piece.Builder getPiecesBuilder(
        int index) {
      return getPiecesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public com.gomokumaster.proto.PieceOrBuilder getPiecesOrBuilder(
        int index) {
      if (piecesBuilder_ == null) {
        return pieces_.get(index);  } else {
        return piecesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public java.util.List<? extends com.gomokumaster.proto.PieceOrBuilder> 
         getPiecesOrBuilderList() {
      if (piecesBuilder_ != null) {
        return piecesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pieces_);
      }
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public com.gomokumaster.proto.Piece.Builder addPiecesBuilder() {
      return getPiecesFieldBuilder().addBuilder(
          com.gomokumaster.proto.Piece.getDefaultInstance());
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public com.gomokumaster.proto.Piece.Builder addPiecesBuilder(
        int index) {
      return getPiecesFieldBuilder().addBuilder(
          index, com.gomokumaster.proto.Piece.getDefaultInstance());
    }
    /**
     * <pre>
     *可以理解为List&lt;Piece&gt;
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
     */
    public java.util.List<com.gomokumaster.proto.Piece.Builder> 
         getPiecesBuilderList() {
      return getPiecesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gomokumaster.proto.Piece, com.gomokumaster.proto.Piece.Builder, com.gomokumaster.proto.PieceOrBuilder> 
        getPiecesFieldBuilder() {
      if (piecesBuilder_ == null) {
        piecesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.gomokumaster.proto.Piece, com.gomokumaster.proto.Piece.Builder, com.gomokumaster.proto.PieceOrBuilder>(
                pieces_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        pieces_ = null;
      }
      return piecesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.gomokumaster.proto.BoardRow)
  }

  // @@protoc_insertion_point(class_scope:com.gomokumaster.proto.BoardRow)
  private static final com.gomokumaster.proto.BoardRow DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gomokumaster.proto.BoardRow();
  }

  public static com.gomokumaster.proto.BoardRow getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BoardRow>
      PARSER = new com.google.protobuf.AbstractParser<BoardRow>() {
    public BoardRow parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new BoardRow(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BoardRow> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BoardRow> getParserForType() {
    return PARSER;
  }

  public com.gomokumaster.proto.BoardRow getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

