// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

public interface BoardRowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gomokumaster.proto.BoardRow)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *可以理解为List&lt;Piece&gt;
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
   */
  java.util.List<com.gomokumaster.proto.Piece> 
      getPiecesList();
  /**
   * <pre>
   *可以理解为List&lt;Piece&gt;
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
   */
  com.gomokumaster.proto.Piece getPieces(int index);
  /**
   * <pre>
   *可以理解为List&lt;Piece&gt;
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
   */
  int getPiecesCount();
  /**
   * <pre>
   *可以理解为List&lt;Piece&gt;
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
   */
  java.util.List<? extends com.gomokumaster.proto.PieceOrBuilder> 
      getPiecesOrBuilderList();
  /**
   * <pre>
   *可以理解为List&lt;Piece&gt;
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.Piece pieces = 1;</code>
   */
  com.gomokumaster.proto.PieceOrBuilder getPiecesOrBuilder(
      int index);
}
