// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

public interface ChatReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gomokumaster.proto.ChatReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int32 senderColor = 2;</code>
   */
  int getSenderColor();

  /**
   * <code>string time = 3;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string text = 4;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 4;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
