// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

public final class GameMsgProtocol {
  private GameMsgProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gomokumaster_proto_MoveReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gomokumaster_proto_MoveReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gomokumaster_proto_Piece_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gomokumaster_proto_Piece_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gomokumaster_proto_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gomokumaster_proto_Player_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gomokumaster_proto_GameSnapshot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gomokumaster_proto_GameSnapshot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gomokumaster_proto_BoardRow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gomokumaster_proto_BoardRow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gomokumaster_proto_ServerNotice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gomokumaster_proto_ServerNotice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gomokumaster_proto_ChatReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gomokumaster_proto_ChatReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gomokumaster_proto_Surrender_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gomokumaster_proto_Surrender_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gomokumaster_proto_GamePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gomokumaster_proto_GamePacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src/main/resources/proto/game.proto\022\026c" +
      "om.gomokumaster.proto\"\206\001\n\007MoveReq\022\t\n\001x\030\001" +
      " \001(\005\022\t\n\001y\030\002 \001(\005\022\021\n\tpieceType\030\003 \001(\t\0220\n\004ty" +
      "pe\030\004 \001(\0162\".com.gomokumaster.proto.PlayAc" +
      "tion\022\017\n\007targetX\030\005 \001(\005\022\017\n\007targetY\030\006 \001(\005\"\260" +
      "\001\n\005Piece\022\n\n\002id\030\001 \001(\t\022\t\n\001x\030\002 \001(\005\022\t\n\001y\030\003 \001" +
      "(\005\022\017\n\007ownerId\030\005 \001(\t\0224\n\tpieceType\030\006 \001(\0162!" +
      ".com.gomokumaster.proto.PieceType\022\r\n\005max" +
      "Cd\030\007 \001(\005\022\r\n\005color\030\010 \001(\005\022\017\n\007isAlive\030\t \001(\010" +
      "\022\017\n\007skillCd\030\013 \001(\005\"\261\001\n\006Player\022\n\n\002id\030\001 \001(\t",
      "\022\014\n\004name\030\002 \001(\t\022\016\n\006avatar\030\003 \001(\t\022\r\n\005color\030" +
      "\004 \001(\005\022\034\n\024remainingShieldCount\030\005 \001(\005\022\034\n\024r" +
      "emainingArcherCount\030\006 \001(\005\022\035\n\025remainingCa" +
      "valryCount\030\007 \001(\005\022\023\n\013isConnected\030\010 \001(\010\"\245\002" +
      "\n\014GameSnapshot\022\016\n\006roomId\030\001 \001(\t\022/\n\005board\030" +
      "\002 \003(\0132 .com.gomokumaster.proto.BoardRow\022" +
      "0\n\010yourInfo\030\003 \001(\0132\036.com.gomokumaster.pro" +
      "to.Player\0220\n\010opponent\030\004 \001(\0132\036.com.gomoku" +
      "master.proto.Player\022\025\n\rcurrentTurnId\030\005 \001" +
      "(\005\0222\n\006status\030\006 \001(\0162\".com.gomokumaster.pr",
      "oto.GameStatus\022\021\n\tyourColor\030\007 \001(\t\022\022\n\nlas" +
      "tAction\030\010 \001(\t\"9\n\010BoardRow\022-\n\006pieces\030\001 \003(" +
      "\0132\035.com.gomokumaster.proto.Piece\"\037\n\014Serv" +
      "erNotice\022\017\n\007message\030\001 \001(\t\"F\n\007ChatReq\022\n\n\002" +
      "id\030\001 \001(\t\022\023\n\013senderColor\030\002 \001(\005\022\014\n\004time\030\003 " +
      "\001(\t\022\014\n\004text\030\004 \001(\t\"C\n\tSurrender\022\n\n\002id\030\001 \001" +
      "(\t\022\014\n\004time\030\002 \001(\t\022\014\n\004text\030\003 \001(\t\022\016\n\006isSelf" +
      "\030\004 \001(\010\"\236\003\n\nGamePacket\022-\n\004type\030\001 \001(\0162\037.co" +
      "m.gomokumaster.proto.MsgType\0222\n\007moveReq\030" +
      "\002 \001(\0132\037.com.gomokumaster.proto.MoveReqH\000",
      "\022<\n\014gameSnapshot\030\003 \001(\0132$.com.gomokumaste" +
      "r.proto.GameSnapshotH\000\0226\n\006notice\030\004 \001(\0132$" +
      ".com.gomokumaster.proto.ServerNoticeH\000\0222" +
      "\n\007chatReq\030\005 \001(\0132\037.com.gomokumaster.proto" +
      ".ChatReqH\000\0226\n\tsurrender\030\006 \001(\0132!.com.gomo" +
      "kumaster.proto.SurrenderH\000\022\022\n\010winnerId\030\007" +
      " \001(\tH\000\022\026\n\014turnDeadline\030\n \001(\003H\000\022\027\n\roppone" +
      "ntColor\030\013 \001(\005H\000B\006\n\004body*\373\001\n\007MsgType\022\013\n\007U" +
      "NKNOWN\020\000\022\016\n\tMATCH_REQ\020\351\007\022\021\n\014MATCH_CANCEL" +
      "\020\352\007\022\016\n\tMATCH_RES\020\353\007\022\r\n\010MOVE_REQ\020\354\007\022\021\n\014BO",
      "ARD_UPDATE\020\355\007\022\016\n\tGAME_OVER\020\356\007\022\r\n\010CHAT_RE" +
      "Q\020\357\007\022\r\n\010CHAT_RES\020\360\007\022\n\n\005ERROR\020\361\007\022\016\n\tSURRE" +
      "NDER\020\363\007\022\014\n\007CONNECT\020\364\007\022\020\n\013GAME_RESUME\020\365\007\022" +
      "\016\n\tHEARTBEAT\020\366\007\022\024\n\017GAME_DISCONNECT\020\367\007*6\n" +
      "\nPlayAction\022\010\n\004NONE\020\000\022\010\n\004MOVE\020\001\022\t\n\005SKILL" +
      "\020\002\022\t\n\005PLACE\020\003*G\n\tPieceType\022\t\n\005EMPTY\020\000\022\n\n" +
      "\006NORMAL\020\001\022\n\n\006ARCHER\020\002\022\013\n\007CAVALRY\020\003\022\n\n\006SH" +
      "IELD\020\004*@\n\nGameStatus\022\013\n\007WAITING\020\000\022\013\n\007STA" +
      "RTED\020\001\022\014\n\010FINISHED\020\002\022\n\n\006PAUSED\020\003B\023B\017Game" +
      "MsgProtocolP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_gomokumaster_proto_MoveReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gomokumaster_proto_MoveReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gomokumaster_proto_MoveReq_descriptor,
        new java.lang.String[] { "X", "Y", "PieceType", "Type", "TargetX", "TargetY", });
    internal_static_com_gomokumaster_proto_Piece_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gomokumaster_proto_Piece_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gomokumaster_proto_Piece_descriptor,
        new java.lang.String[] { "Id", "X", "Y", "OwnerId", "PieceType", "MaxCd", "Color", "IsAlive", "SkillCd", });
    internal_static_com_gomokumaster_proto_Player_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_gomokumaster_proto_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gomokumaster_proto_Player_descriptor,
        new java.lang.String[] { "Id", "Name", "Avatar", "Color", "RemainingShieldCount", "RemainingArcherCount", "RemainingCavalryCount", "IsConnected", });
    internal_static_com_gomokumaster_proto_GameSnapshot_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_gomokumaster_proto_GameSnapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gomokumaster_proto_GameSnapshot_descriptor,
        new java.lang.String[] { "RoomId", "Board", "YourInfo", "Opponent", "CurrentTurnId", "Status", "YourColor", "LastAction", });
    internal_static_com_gomokumaster_proto_BoardRow_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_gomokumaster_proto_BoardRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gomokumaster_proto_BoardRow_descriptor,
        new java.lang.String[] { "Pieces", });
    internal_static_com_gomokumaster_proto_ServerNotice_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_gomokumaster_proto_ServerNotice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gomokumaster_proto_ServerNotice_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_gomokumaster_proto_ChatReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_gomokumaster_proto_ChatReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gomokumaster_proto_ChatReq_descriptor,
        new java.lang.String[] { "Id", "SenderColor", "Time", "Text", });
    internal_static_com_gomokumaster_proto_Surrender_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_gomokumaster_proto_Surrender_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gomokumaster_proto_Surrender_descriptor,
        new java.lang.String[] { "Id", "Time", "Text", "IsSelf", });
    internal_static_com_gomokumaster_proto_GamePacket_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_gomokumaster_proto_GamePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gomokumaster_proto_GamePacket_descriptor,
        new java.lang.String[] { "Type", "MoveReq", "GameSnapshot", "Notice", "ChatReq", "Surrender", "WinnerId", "TurnDeadline", "OpponentColor", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
