// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

/**
 * Protobuf enum {@code com.gomokumaster.proto.GameStatus}
 */
public enum GameStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>WAITING = 0;</code>
   */
  WAITING(0),
  /**
   * <code>STARTED = 1;</code>
   */
  STARTED(1),
  /**
   * <code>FINISHED = 2;</code>
   */
  FINISHED(2),
  /**
   * <code>PAUSED = 3;</code>
   */
  PAUSED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>WAITING = 0;</code>
   */
  public static final int WAITING_VALUE = 0;
  /**
   * <code>STARTED = 1;</code>
   */
  public static final int STARTED_VALUE = 1;
  /**
   * <code>FINISHED = 2;</code>
   */
  public static final int FINISHED_VALUE = 2;
  /**
   * <code>PAUSED = 3;</code>
   */
  public static final int PAUSED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GameStatus valueOf(int value) {
    return forNumber(value);
  }

  public static GameStatus forNumber(int value) {
    switch (value) {
      case 0: return WAITING;
      case 1: return STARTED;
      case 2: return FINISHED;
      case 3: return PAUSED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GameStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GameStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GameStatus>() {
          public GameStatus findValueByNumber(int number) {
            return GameStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.gomokumaster.proto.GameMsgProtocol.getDescriptor().getEnumTypes().get(3);
  }

  private static final GameStatus[] VALUES = values();

  public static GameStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private GameStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.gomokumaster.proto.GameStatus)
}

