// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

/**
 * <pre>
 *每次下棋都会更新
 * </pre>
 *
 * Protobuf type {@code com.gomokumaster.proto.GameSnapshot}
 */
public  final class GameSnapshot extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gomokumaster.proto.GameSnapshot)
    GameSnapshotOrBuilder {
  // Use GameSnapshot.newBuilder() to construct.
  private GameSnapshot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GameSnapshot() {
    roomId_ = "";
    board_ = java.util.Collections.emptyList();
    currentTurnId_ = 0;
    status_ = 0;
    yourColor_ = "";
    lastAction_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GameSnapshot(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            roomId_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              board_ = new java.util.ArrayList<com.gomokumaster.proto.BoardRow>();
              mutable_bitField0_ |= 0x00000002;
            }
            board_.add(
                input.readMessage(com.gomokumaster.proto.BoardRow.parser(), extensionRegistry));
            break;
          }
          case 26: {
            com.gomokumaster.proto.Player.Builder subBuilder = null;
            if (yourInfo_ != null) {
              subBuilder = yourInfo_.toBuilder();
            }
            yourInfo_ = input.readMessage(com.gomokumaster.proto.Player.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(yourInfo_);
              yourInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.gomokumaster.proto.Player.Builder subBuilder = null;
            if (opponent_ != null) {
              subBuilder = opponent_.toBuilder();
            }
            opponent_ = input.readMessage(com.gomokumaster.proto.Player.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(opponent_);
              opponent_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {

            currentTurnId_ = input.readInt32();
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            yourColor_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            lastAction_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        board_ = java.util.Collections.unmodifiableList(board_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_GameSnapshot_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_GameSnapshot_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gomokumaster.proto.GameSnapshot.class, com.gomokumaster.proto.GameSnapshot.Builder.class);
  }

  private int bitField0_;
  public static final int ROOMID_FIELD_NUMBER = 1;
  private volatile java.lang.Object roomId_;
  /**
   * <code>string roomId = 1;</code>
   */
  public java.lang.String getRoomId() {
    java.lang.Object ref = roomId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomId_ = s;
      return s;
    }
  }
  /**
   * <code>string roomId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRoomIdBytes() {
    java.lang.Object ref = roomId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOARD_FIELD_NUMBER = 2;
  private java.util.List<com.gomokumaster.proto.BoardRow> board_;
  /**
   * <pre>
   *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
   */
  public java.util.List<com.gomokumaster.proto.BoardRow> getBoardList() {
    return board_;
  }
  /**
   * <pre>
   *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
   */
  public java.util.List<? extends com.gomokumaster.proto.BoardRowOrBuilder> 
      getBoardOrBuilderList() {
    return board_;
  }
  /**
   * <pre>
   *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
   */
  public int getBoardCount() {
    return board_.size();
  }
  /**
   * <pre>
   *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
   */
  public com.gomokumaster.proto.BoardRow getBoard(int index) {
    return board_.get(index);
  }
  /**
   * <pre>
   *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
   */
  public com.gomokumaster.proto.BoardRowOrBuilder getBoardOrBuilder(
      int index) {
    return board_.get(index);
  }

  public static final int YOURINFO_FIELD_NUMBER = 3;
  private com.gomokumaster.proto.Player yourInfo_;
  /**
   * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
   */
  public boolean hasYourInfo() {
    return yourInfo_ != null;
  }
  /**
   * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
   */
  public com.gomokumaster.proto.Player getYourInfo() {
    return yourInfo_ == null ? com.gomokumaster.proto.Player.getDefaultInstance() : yourInfo_;
  }
  /**
   * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
   */
  public com.gomokumaster.proto.PlayerOrBuilder getYourInfoOrBuilder() {
    return getYourInfo();
  }

  public static final int OPPONENT_FIELD_NUMBER = 4;
  private com.gomokumaster.proto.Player opponent_;
  /**
   * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
   */
  public boolean hasOpponent() {
    return opponent_ != null;
  }
  /**
   * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
   */
  public com.gomokumaster.proto.Player getOpponent() {
    return opponent_ == null ? com.gomokumaster.proto.Player.getDefaultInstance() : opponent_;
  }
  /**
   * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
   */
  public com.gomokumaster.proto.PlayerOrBuilder getOpponentOrBuilder() {
    return getOpponent();
  }

  public static final int CURRENTTURNID_FIELD_NUMBER = 5;
  private int currentTurnId_;
  /**
   * <code>int32 currentTurnId = 5;</code>
   */
  public int getCurrentTurnId() {
    return currentTurnId_;
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  private int status_;
  /**
   * <code>.com.gomokumaster.proto.GameStatus status = 6;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.com.gomokumaster.proto.GameStatus status = 6;</code>
   */
  public com.gomokumaster.proto.GameStatus getStatus() {
    com.gomokumaster.proto.GameStatus result = com.gomokumaster.proto.GameStatus.valueOf(status_);
    return result == null ? com.gomokumaster.proto.GameStatus.UNRECOGNIZED : result;
  }

  public static final int YOURCOLOR_FIELD_NUMBER = 7;
  private volatile java.lang.Object yourColor_;
  /**
   * <code>string yourColor = 7;</code>
   */
  public java.lang.String getYourColor() {
    java.lang.Object ref = yourColor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      yourColor_ = s;
      return s;
    }
  }
  /**
   * <code>string yourColor = 7;</code>
   */
  public com.google.protobuf.ByteString
      getYourColorBytes() {
    java.lang.Object ref = yourColor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      yourColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTACTION_FIELD_NUMBER = 8;
  private volatile java.lang.Object lastAction_;
  /**
   * <code>string lastAction = 8;</code>
   */
  public java.lang.String getLastAction() {
    java.lang.Object ref = lastAction_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastAction_ = s;
      return s;
    }
  }
  /**
   * <code>string lastAction = 8;</code>
   */
  public com.google.protobuf.ByteString
      getLastActionBytes() {
    java.lang.Object ref = lastAction_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastAction_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRoomIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, roomId_);
    }
    for (int i = 0; i < board_.size(); i++) {
      output.writeMessage(2, board_.get(i));
    }
    if (yourInfo_ != null) {
      output.writeMessage(3, getYourInfo());
    }
    if (opponent_ != null) {
      output.writeMessage(4, getOpponent());
    }
    if (currentTurnId_ != 0) {
      output.writeInt32(5, currentTurnId_);
    }
    if (status_ != com.gomokumaster.proto.GameStatus.WAITING.getNumber()) {
      output.writeEnum(6, status_);
    }
    if (!getYourColorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, yourColor_);
    }
    if (!getLastActionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, lastAction_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRoomIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, roomId_);
    }
    for (int i = 0; i < board_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, board_.get(i));
    }
    if (yourInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getYourInfo());
    }
    if (opponent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getOpponent());
    }
    if (currentTurnId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, currentTurnId_);
    }
    if (status_ != com.gomokumaster.proto.GameStatus.WAITING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, status_);
    }
    if (!getYourColorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, yourColor_);
    }
    if (!getLastActionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, lastAction_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gomokumaster.proto.GameSnapshot)) {
      return super.equals(obj);
    }
    com.gomokumaster.proto.GameSnapshot other = (com.gomokumaster.proto.GameSnapshot) obj;

    boolean result = true;
    result = result && getRoomId()
        .equals(other.getRoomId());
    result = result && getBoardList()
        .equals(other.getBoardList());
    result = result && (hasYourInfo() == other.hasYourInfo());
    if (hasYourInfo()) {
      result = result && getYourInfo()
          .equals(other.getYourInfo());
    }
    result = result && (hasOpponent() == other.hasOpponent());
    if (hasOpponent()) {
      result = result && getOpponent()
          .equals(other.getOpponent());
    }
    result = result && (getCurrentTurnId()
        == other.getCurrentTurnId());
    result = result && status_ == other.status_;
    result = result && getYourColor()
        .equals(other.getYourColor());
    result = result && getLastAction()
        .equals(other.getLastAction());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROOMID_FIELD_NUMBER;
    hash = (53 * hash) + getRoomId().hashCode();
    if (getBoardCount() > 0) {
      hash = (37 * hash) + BOARD_FIELD_NUMBER;
      hash = (53 * hash) + getBoardList().hashCode();
    }
    if (hasYourInfo()) {
      hash = (37 * hash) + YOURINFO_FIELD_NUMBER;
      hash = (53 * hash) + getYourInfo().hashCode();
    }
    if (hasOpponent()) {
      hash = (37 * hash) + OPPONENT_FIELD_NUMBER;
      hash = (53 * hash) + getOpponent().hashCode();
    }
    hash = (37 * hash) + CURRENTTURNID_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentTurnId();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + YOURCOLOR_FIELD_NUMBER;
    hash = (53 * hash) + getYourColor().hashCode();
    hash = (37 * hash) + LASTACTION_FIELD_NUMBER;
    hash = (53 * hash) + getLastAction().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gomokumaster.proto.GameSnapshot parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gomokumaster.proto.GameSnapshot parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gomokumaster.proto.GameSnapshot parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gomokumaster.proto.GameSnapshot parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gomokumaster.proto.GameSnapshot parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.GameSnapshot parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gomokumaster.proto.GameSnapshot parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.GameSnapshot parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gomokumaster.proto.GameSnapshot parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.GameSnapshot parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gomokumaster.proto.GameSnapshot prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *每次下棋都会更新
   * </pre>
   *
   * Protobuf type {@code com.gomokumaster.proto.GameSnapshot}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gomokumaster.proto.GameSnapshot)
      com.gomokumaster.proto.GameSnapshotOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_GameSnapshot_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_GameSnapshot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gomokumaster.proto.GameSnapshot.class, com.gomokumaster.proto.GameSnapshot.Builder.class);
    }

    // Construct using com.gomokumaster.proto.GameSnapshot.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBoardFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      roomId_ = "";

      if (boardBuilder_ == null) {
        board_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        boardBuilder_.clear();
      }
      if (yourInfoBuilder_ == null) {
        yourInfo_ = null;
      } else {
        yourInfo_ = null;
        yourInfoBuilder_ = null;
      }
      if (opponentBuilder_ == null) {
        opponent_ = null;
      } else {
        opponent_ = null;
        opponentBuilder_ = null;
      }
      currentTurnId_ = 0;

      status_ = 0;

      yourColor_ = "";

      lastAction_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_GameSnapshot_descriptor;
    }

    public com.gomokumaster.proto.GameSnapshot getDefaultInstanceForType() {
      return com.gomokumaster.proto.GameSnapshot.getDefaultInstance();
    }

    public com.gomokumaster.proto.GameSnapshot build() {
      com.gomokumaster.proto.GameSnapshot result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.gomokumaster.proto.GameSnapshot buildPartial() {
      com.gomokumaster.proto.GameSnapshot result = new com.gomokumaster.proto.GameSnapshot(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.roomId_ = roomId_;
      if (boardBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          board_ = java.util.Collections.unmodifiableList(board_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.board_ = board_;
      } else {
        result.board_ = boardBuilder_.build();
      }
      if (yourInfoBuilder_ == null) {
        result.yourInfo_ = yourInfo_;
      } else {
        result.yourInfo_ = yourInfoBuilder_.build();
      }
      if (opponentBuilder_ == null) {
        result.opponent_ = opponent_;
      } else {
        result.opponent_ = opponentBuilder_.build();
      }
      result.currentTurnId_ = currentTurnId_;
      result.status_ = status_;
      result.yourColor_ = yourColor_;
      result.lastAction_ = lastAction_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gomokumaster.proto.GameSnapshot) {
        return mergeFrom((com.gomokumaster.proto.GameSnapshot)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gomokumaster.proto.GameSnapshot other) {
      if (other == com.gomokumaster.proto.GameSnapshot.getDefaultInstance()) return this;
      if (!other.getRoomId().isEmpty()) {
        roomId_ = other.roomId_;
        onChanged();
      }
      if (boardBuilder_ == null) {
        if (!other.board_.isEmpty()) {
          if (board_.isEmpty()) {
            board_ = other.board_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBoardIsMutable();
            board_.addAll(other.board_);
          }
          onChanged();
        }
      } else {
        if (!other.board_.isEmpty()) {
          if (boardBuilder_.isEmpty()) {
            boardBuilder_.dispose();
            boardBuilder_ = null;
            board_ = other.board_;
            bitField0_ = (bitField0_ & ~0x00000002);
            boardBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBoardFieldBuilder() : null;
          } else {
            boardBuilder_.addAllMessages(other.board_);
          }
        }
      }
      if (other.hasYourInfo()) {
        mergeYourInfo(other.getYourInfo());
      }
      if (other.hasOpponent()) {
        mergeOpponent(other.getOpponent());
      }
      if (other.getCurrentTurnId() != 0) {
        setCurrentTurnId(other.getCurrentTurnId());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getYourColor().isEmpty()) {
        yourColor_ = other.yourColor_;
        onChanged();
      }
      if (!other.getLastAction().isEmpty()) {
        lastAction_ = other.lastAction_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gomokumaster.proto.GameSnapshot parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gomokumaster.proto.GameSnapshot) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object roomId_ = "";
    /**
     * <code>string roomId = 1;</code>
     */
    public java.lang.String getRoomId() {
      java.lang.Object ref = roomId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string roomId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoomIdBytes() {
      java.lang.Object ref = roomId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string roomId = 1;</code>
     */
    public Builder setRoomId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roomId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string roomId = 1;</code>
     */
    public Builder clearRoomId() {
      
      roomId_ = getDefaultInstance().getRoomId();
      onChanged();
      return this;
    }
    /**
     * <code>string roomId = 1;</code>
     */
    public Builder setRoomIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roomId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.gomokumaster.proto.BoardRow> board_ =
      java.util.Collections.emptyList();
    private void ensureBoardIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        board_ = new java.util.ArrayList<com.gomokumaster.proto.BoardRow>(board_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gomokumaster.proto.BoardRow, com.gomokumaster.proto.BoardRow.Builder, com.gomokumaster.proto.BoardRowOrBuilder> boardBuilder_;

    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public java.util.List<com.gomokumaster.proto.BoardRow> getBoardList() {
      if (boardBuilder_ == null) {
        return java.util.Collections.unmodifiableList(board_);
      } else {
        return boardBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public int getBoardCount() {
      if (boardBuilder_ == null) {
        return board_.size();
      } else {
        return boardBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public com.gomokumaster.proto.BoardRow getBoard(int index) {
      if (boardBuilder_ == null) {
        return board_.get(index);
      } else {
        return boardBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public Builder setBoard(
        int index, com.gomokumaster.proto.BoardRow value) {
      if (boardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBoardIsMutable();
        board_.set(index, value);
        onChanged();
      } else {
        boardBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public Builder setBoard(
        int index, com.gomokumaster.proto.BoardRow.Builder builderForValue) {
      if (boardBuilder_ == null) {
        ensureBoardIsMutable();
        board_.set(index, builderForValue.build());
        onChanged();
      } else {
        boardBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public Builder addBoard(com.gomokumaster.proto.BoardRow value) {
      if (boardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBoardIsMutable();
        board_.add(value);
        onChanged();
      } else {
        boardBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public Builder addBoard(
        int index, com.gomokumaster.proto.BoardRow value) {
      if (boardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBoardIsMutable();
        board_.add(index, value);
        onChanged();
      } else {
        boardBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public Builder addBoard(
        com.gomokumaster.proto.BoardRow.Builder builderForValue) {
      if (boardBuilder_ == null) {
        ensureBoardIsMutable();
        board_.add(builderForValue.build());
        onChanged();
      } else {
        boardBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public Builder addBoard(
        int index, com.gomokumaster.proto.BoardRow.Builder builderForValue) {
      if (boardBuilder_ == null) {
        ensureBoardIsMutable();
        board_.add(index, builderForValue.build());
        onChanged();
      } else {
        boardBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public Builder addAllBoard(
        java.lang.Iterable<? extends com.gomokumaster.proto.BoardRow> values) {
      if (boardBuilder_ == null) {
        ensureBoardIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, board_);
        onChanged();
      } else {
        boardBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public Builder clearBoard() {
      if (boardBuilder_ == null) {
        board_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        boardBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public Builder removeBoard(int index) {
      if (boardBuilder_ == null) {
        ensureBoardIsMutable();
        board_.remove(index);
        onChanged();
      } else {
        boardBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public com.gomokumaster.proto.BoardRow.Builder getBoardBuilder(
        int index) {
      return getBoardFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public com.gomokumaster.proto.BoardRowOrBuilder getBoardOrBuilder(
        int index) {
      if (boardBuilder_ == null) {
        return board_.get(index);  } else {
        return boardBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public java.util.List<? extends com.gomokumaster.proto.BoardRowOrBuilder> 
         getBoardOrBuilderList() {
      if (boardBuilder_ != null) {
        return boardBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(board_);
      }
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public com.gomokumaster.proto.BoardRow.Builder addBoardBuilder() {
      return getBoardFieldBuilder().addBuilder(
          com.gomokumaster.proto.BoardRow.getDefaultInstance());
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public com.gomokumaster.proto.BoardRow.Builder addBoardBuilder(
        int index) {
      return getBoardFieldBuilder().addBuilder(
          index, com.gomokumaster.proto.BoardRow.getDefaultInstance());
    }
    /**
     * <pre>
     *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
     * </pre>
     *
     * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
     */
    public java.util.List<com.gomokumaster.proto.BoardRow.Builder> 
         getBoardBuilderList() {
      return getBoardFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gomokumaster.proto.BoardRow, com.gomokumaster.proto.BoardRow.Builder, com.gomokumaster.proto.BoardRowOrBuilder> 
        getBoardFieldBuilder() {
      if (boardBuilder_ == null) {
        boardBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.gomokumaster.proto.BoardRow, com.gomokumaster.proto.BoardRow.Builder, com.gomokumaster.proto.BoardRowOrBuilder>(
                board_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        board_ = null;
      }
      return boardBuilder_;
    }

    private com.gomokumaster.proto.Player yourInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.Player, com.gomokumaster.proto.Player.Builder, com.gomokumaster.proto.PlayerOrBuilder> yourInfoBuilder_;
    /**
     * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
     */
    public boolean hasYourInfo() {
      return yourInfoBuilder_ != null || yourInfo_ != null;
    }
    /**
     * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
     */
    public com.gomokumaster.proto.Player getYourInfo() {
      if (yourInfoBuilder_ == null) {
        return yourInfo_ == null ? com.gomokumaster.proto.Player.getDefaultInstance() : yourInfo_;
      } else {
        return yourInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
     */
    public Builder setYourInfo(com.gomokumaster.proto.Player value) {
      if (yourInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        yourInfo_ = value;
        onChanged();
      } else {
        yourInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
     */
    public Builder setYourInfo(
        com.gomokumaster.proto.Player.Builder builderForValue) {
      if (yourInfoBuilder_ == null) {
        yourInfo_ = builderForValue.build();
        onChanged();
      } else {
        yourInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
     */
    public Builder mergeYourInfo(com.gomokumaster.proto.Player value) {
      if (yourInfoBuilder_ == null) {
        if (yourInfo_ != null) {
          yourInfo_ =
            com.gomokumaster.proto.Player.newBuilder(yourInfo_).mergeFrom(value).buildPartial();
        } else {
          yourInfo_ = value;
        }
        onChanged();
      } else {
        yourInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
     */
    public Builder clearYourInfo() {
      if (yourInfoBuilder_ == null) {
        yourInfo_ = null;
        onChanged();
      } else {
        yourInfo_ = null;
        yourInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
     */
    public com.gomokumaster.proto.Player.Builder getYourInfoBuilder() {
      
      onChanged();
      return getYourInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
     */
    public com.gomokumaster.proto.PlayerOrBuilder getYourInfoOrBuilder() {
      if (yourInfoBuilder_ != null) {
        return yourInfoBuilder_.getMessageOrBuilder();
      } else {
        return yourInfo_ == null ?
            com.gomokumaster.proto.Player.getDefaultInstance() : yourInfo_;
      }
    }
    /**
     * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.Player, com.gomokumaster.proto.Player.Builder, com.gomokumaster.proto.PlayerOrBuilder> 
        getYourInfoFieldBuilder() {
      if (yourInfoBuilder_ == null) {
        yourInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gomokumaster.proto.Player, com.gomokumaster.proto.Player.Builder, com.gomokumaster.proto.PlayerOrBuilder>(
                getYourInfo(),
                getParentForChildren(),
                isClean());
        yourInfo_ = null;
      }
      return yourInfoBuilder_;
    }

    private com.gomokumaster.proto.Player opponent_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.Player, com.gomokumaster.proto.Player.Builder, com.gomokumaster.proto.PlayerOrBuilder> opponentBuilder_;
    /**
     * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
     */
    public boolean hasOpponent() {
      return opponentBuilder_ != null || opponent_ != null;
    }
    /**
     * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
     */
    public com.gomokumaster.proto.Player getOpponent() {
      if (opponentBuilder_ == null) {
        return opponent_ == null ? com.gomokumaster.proto.Player.getDefaultInstance() : opponent_;
      } else {
        return opponentBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
     */
    public Builder setOpponent(com.gomokumaster.proto.Player value) {
      if (opponentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        opponent_ = value;
        onChanged();
      } else {
        opponentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
     */
    public Builder setOpponent(
        com.gomokumaster.proto.Player.Builder builderForValue) {
      if (opponentBuilder_ == null) {
        opponent_ = builderForValue.build();
        onChanged();
      } else {
        opponentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
     */
    public Builder mergeOpponent(com.gomokumaster.proto.Player value) {
      if (opponentBuilder_ == null) {
        if (opponent_ != null) {
          opponent_ =
            com.gomokumaster.proto.Player.newBuilder(opponent_).mergeFrom(value).buildPartial();
        } else {
          opponent_ = value;
        }
        onChanged();
      } else {
        opponentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
     */
    public Builder clearOpponent() {
      if (opponentBuilder_ == null) {
        opponent_ = null;
        onChanged();
      } else {
        opponent_ = null;
        opponentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
     */
    public com.gomokumaster.proto.Player.Builder getOpponentBuilder() {
      
      onChanged();
      return getOpponentFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
     */
    public com.gomokumaster.proto.PlayerOrBuilder getOpponentOrBuilder() {
      if (opponentBuilder_ != null) {
        return opponentBuilder_.getMessageOrBuilder();
      } else {
        return opponent_ == null ?
            com.gomokumaster.proto.Player.getDefaultInstance() : opponent_;
      }
    }
    /**
     * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.Player, com.gomokumaster.proto.Player.Builder, com.gomokumaster.proto.PlayerOrBuilder> 
        getOpponentFieldBuilder() {
      if (opponentBuilder_ == null) {
        opponentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gomokumaster.proto.Player, com.gomokumaster.proto.Player.Builder, com.gomokumaster.proto.PlayerOrBuilder>(
                getOpponent(),
                getParentForChildren(),
                isClean());
        opponent_ = null;
      }
      return opponentBuilder_;
    }

    private int currentTurnId_ ;
    /**
     * <code>int32 currentTurnId = 5;</code>
     */
    public int getCurrentTurnId() {
      return currentTurnId_;
    }
    /**
     * <code>int32 currentTurnId = 5;</code>
     */
    public Builder setCurrentTurnId(int value) {
      
      currentTurnId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 currentTurnId = 5;</code>
     */
    public Builder clearCurrentTurnId() {
      
      currentTurnId_ = 0;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.com.gomokumaster.proto.GameStatus status = 6;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.gomokumaster.proto.GameStatus status = 6;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.GameStatus status = 6;</code>
     */
    public com.gomokumaster.proto.GameStatus getStatus() {
      com.gomokumaster.proto.GameStatus result = com.gomokumaster.proto.GameStatus.valueOf(status_);
      return result == null ? com.gomokumaster.proto.GameStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.gomokumaster.proto.GameStatus status = 6;</code>
     */
    public Builder setStatus(com.gomokumaster.proto.GameStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.GameStatus status = 6;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object yourColor_ = "";
    /**
     * <code>string yourColor = 7;</code>
     */
    public java.lang.String getYourColor() {
      java.lang.Object ref = yourColor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        yourColor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string yourColor = 7;</code>
     */
    public com.google.protobuf.ByteString
        getYourColorBytes() {
      java.lang.Object ref = yourColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        yourColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string yourColor = 7;</code>
     */
    public Builder setYourColor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      yourColor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string yourColor = 7;</code>
     */
    public Builder clearYourColor() {
      
      yourColor_ = getDefaultInstance().getYourColor();
      onChanged();
      return this;
    }
    /**
     * <code>string yourColor = 7;</code>
     */
    public Builder setYourColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      yourColor_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastAction_ = "";
    /**
     * <code>string lastAction = 8;</code>
     */
    public java.lang.String getLastAction() {
      java.lang.Object ref = lastAction_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastAction_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastAction = 8;</code>
     */
    public com.google.protobuf.ByteString
        getLastActionBytes() {
      java.lang.Object ref = lastAction_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastAction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastAction = 8;</code>
     */
    public Builder setLastAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastAction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lastAction = 8;</code>
     */
    public Builder clearLastAction() {
      
      lastAction_ = getDefaultInstance().getLastAction();
      onChanged();
      return this;
    }
    /**
     * <code>string lastAction = 8;</code>
     */
    public Builder setLastActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastAction_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.gomokumaster.proto.GameSnapshot)
  }

  // @@protoc_insertion_point(class_scope:com.gomokumaster.proto.GameSnapshot)
  private static final com.gomokumaster.proto.GameSnapshot DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gomokumaster.proto.GameSnapshot();
  }

  public static com.gomokumaster.proto.GameSnapshot getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameSnapshot>
      PARSER = new com.google.protobuf.AbstractParser<GameSnapshot>() {
    public GameSnapshot parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameSnapshot(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GameSnapshot> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameSnapshot> getParserForType() {
    return PARSER;
  }

  public com.gomokumaster.proto.GameSnapshot getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

