// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

public interface GameSnapshotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gomokumaster.proto.GameSnapshot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomId = 1;</code>
   */
  java.lang.String getRoomId();
  /**
   * <code>string roomId = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();

  /**
   * <pre>
   *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
   */
  java.util.List<com.gomokumaster.proto.BoardRow> 
      getBoardList();
  /**
   * <pre>
   *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
   */
  com.gomokumaster.proto.BoardRow getBoard(int index);
  /**
   * <pre>
   *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
   */
  int getBoardCount();
  /**
   * <pre>
   *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
   */
  java.util.List<? extends com.gomokumaster.proto.BoardRowOrBuilder> 
      getBoardOrBuilderList();
  /**
   * <pre>
   *可以理解为List&lt;List&lt;Piece&gt;&gt;,或者board[][]
   * </pre>
   *
   * <code>repeated .com.gomokumaster.proto.BoardRow board = 2;</code>
   */
  com.gomokumaster.proto.BoardRowOrBuilder getBoardOrBuilder(
      int index);

  /**
   * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
   */
  boolean hasYourInfo();
  /**
   * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
   */
  com.gomokumaster.proto.Player getYourInfo();
  /**
   * <code>.com.gomokumaster.proto.Player yourInfo = 3;</code>
   */
  com.gomokumaster.proto.PlayerOrBuilder getYourInfoOrBuilder();

  /**
   * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
   */
  boolean hasOpponent();
  /**
   * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
   */
  com.gomokumaster.proto.Player getOpponent();
  /**
   * <code>.com.gomokumaster.proto.Player opponent = 4;</code>
   */
  com.gomokumaster.proto.PlayerOrBuilder getOpponentOrBuilder();

  /**
   * <code>int32 currentTurnId = 5;</code>
   */
  int getCurrentTurnId();

  /**
   * <code>.com.gomokumaster.proto.GameStatus status = 6;</code>
   */
  int getStatusValue();
  /**
   * <code>.com.gomokumaster.proto.GameStatus status = 6;</code>
   */
  com.gomokumaster.proto.GameStatus getStatus();

  /**
   * <code>string yourColor = 7;</code>
   */
  java.lang.String getYourColor();
  /**
   * <code>string yourColor = 7;</code>
   */
  com.google.protobuf.ByteString
      getYourColorBytes();

  /**
   * <code>string lastAction = 8;</code>
   */
  java.lang.String getLastAction();
  /**
   * <code>string lastAction = 8;</code>
   */
  com.google.protobuf.ByteString
      getLastActionBytes();
}
