// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

/**
 * <pre>
 *前后端通信的消息包，包含消息类型和消息体
 * </pre>
 *
 * Protobuf type {@code com.gomokumaster.proto.GamePacket}
 */
public  final class GamePacket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gomokumaster.proto.GamePacket)
    GamePacketOrBuilder {
  // Use GamePacket.newBuilder() to construct.
  private GamePacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GamePacket() {
    type_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GamePacket(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            com.gomokumaster.proto.MoveReq.Builder subBuilder = null;
            if (bodyCase_ == 2) {
              subBuilder = ((com.gomokumaster.proto.MoveReq) body_).toBuilder();
            }
            body_ =
                input.readMessage(com.gomokumaster.proto.MoveReq.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.gomokumaster.proto.MoveReq) body_);
              body_ = subBuilder.buildPartial();
            }
            bodyCase_ = 2;
            break;
          }
          case 26: {
            com.gomokumaster.proto.GameSnapshot.Builder subBuilder = null;
            if (bodyCase_ == 3) {
              subBuilder = ((com.gomokumaster.proto.GameSnapshot) body_).toBuilder();
            }
            body_ =
                input.readMessage(com.gomokumaster.proto.GameSnapshot.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.gomokumaster.proto.GameSnapshot) body_);
              body_ = subBuilder.buildPartial();
            }
            bodyCase_ = 3;
            break;
          }
          case 34: {
            com.gomokumaster.proto.ServerNotice.Builder subBuilder = null;
            if (bodyCase_ == 4) {
              subBuilder = ((com.gomokumaster.proto.ServerNotice) body_).toBuilder();
            }
            body_ =
                input.readMessage(com.gomokumaster.proto.ServerNotice.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.gomokumaster.proto.ServerNotice) body_);
              body_ = subBuilder.buildPartial();
            }
            bodyCase_ = 4;
            break;
          }
          case 42: {
            com.gomokumaster.proto.ChatReq.Builder subBuilder = null;
            if (bodyCase_ == 5) {
              subBuilder = ((com.gomokumaster.proto.ChatReq) body_).toBuilder();
            }
            body_ =
                input.readMessage(com.gomokumaster.proto.ChatReq.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.gomokumaster.proto.ChatReq) body_);
              body_ = subBuilder.buildPartial();
            }
            bodyCase_ = 5;
            break;
          }
          case 50: {
            com.gomokumaster.proto.Surrender.Builder subBuilder = null;
            if (bodyCase_ == 6) {
              subBuilder = ((com.gomokumaster.proto.Surrender) body_).toBuilder();
            }
            body_ =
                input.readMessage(com.gomokumaster.proto.Surrender.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.gomokumaster.proto.Surrender) body_);
              body_ = subBuilder.buildPartial();
            }
            bodyCase_ = 6;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            bodyCase_ = 7;
            body_ = s;
            break;
          }
          case 80: {
            bodyCase_ = 10;
            body_ = input.readInt64();
            break;
          }
          case 88: {
            bodyCase_ = 11;
            body_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_GamePacket_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_GamePacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gomokumaster.proto.GamePacket.class, com.gomokumaster.proto.GamePacket.Builder.class);
  }

  private int bodyCase_ = 0;
  private java.lang.Object body_;
  public enum BodyCase
      implements com.google.protobuf.Internal.EnumLite {
    MOVEREQ(2),
    GAMESNAPSHOT(3),
    NOTICE(4),
    CHATREQ(5),
    SURRENDER(6),
    WINNERID(7),
    TURNDEADLINE(10),
    OPPONENTCOLOR(11),
    BODY_NOT_SET(0);
    private final int value;
    private BodyCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static BodyCase forNumber(int value) {
      switch (value) {
        case 2: return MOVEREQ;
        case 3: return GAMESNAPSHOT;
        case 4: return NOTICE;
        case 5: return CHATREQ;
        case 6: return SURRENDER;
        case 7: return WINNERID;
        case 10: return TURNDEADLINE;
        case 11: return OPPONENTCOLOR;
        case 0: return BODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public BodyCase
  getBodyCase() {
    return BodyCase.forNumber(
        bodyCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.com.gomokumaster.proto.MsgType type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.com.gomokumaster.proto.MsgType type = 1;</code>
   */
  public com.gomokumaster.proto.MsgType getType() {
    com.gomokumaster.proto.MsgType result = com.gomokumaster.proto.MsgType.valueOf(type_);
    return result == null ? com.gomokumaster.proto.MsgType.UNRECOGNIZED : result;
  }

  public static final int MOVEREQ_FIELD_NUMBER = 2;
  /**
   * <code>.com.gomokumaster.proto.MoveReq moveReq = 2;</code>
   */
  public com.gomokumaster.proto.MoveReq getMoveReq() {
    if (bodyCase_ == 2) {
       return (com.gomokumaster.proto.MoveReq) body_;
    }
    return com.gomokumaster.proto.MoveReq.getDefaultInstance();
  }
  /**
   * <code>.com.gomokumaster.proto.MoveReq moveReq = 2;</code>
   */
  public com.gomokumaster.proto.MoveReqOrBuilder getMoveReqOrBuilder() {
    if (bodyCase_ == 2) {
       return (com.gomokumaster.proto.MoveReq) body_;
    }
    return com.gomokumaster.proto.MoveReq.getDefaultInstance();
  }

  public static final int GAMESNAPSHOT_FIELD_NUMBER = 3;
  /**
   * <code>.com.gomokumaster.proto.GameSnapshot gameSnapshot = 3;</code>
   */
  public com.gomokumaster.proto.GameSnapshot getGameSnapshot() {
    if (bodyCase_ == 3) {
       return (com.gomokumaster.proto.GameSnapshot) body_;
    }
    return com.gomokumaster.proto.GameSnapshot.getDefaultInstance();
  }
  /**
   * <code>.com.gomokumaster.proto.GameSnapshot gameSnapshot = 3;</code>
   */
  public com.gomokumaster.proto.GameSnapshotOrBuilder getGameSnapshotOrBuilder() {
    if (bodyCase_ == 3) {
       return (com.gomokumaster.proto.GameSnapshot) body_;
    }
    return com.gomokumaster.proto.GameSnapshot.getDefaultInstance();
  }

  public static final int NOTICE_FIELD_NUMBER = 4;
  /**
   * <code>.com.gomokumaster.proto.ServerNotice notice = 4;</code>
   */
  public com.gomokumaster.proto.ServerNotice getNotice() {
    if (bodyCase_ == 4) {
       return (com.gomokumaster.proto.ServerNotice) body_;
    }
    return com.gomokumaster.proto.ServerNotice.getDefaultInstance();
  }
  /**
   * <code>.com.gomokumaster.proto.ServerNotice notice = 4;</code>
   */
  public com.gomokumaster.proto.ServerNoticeOrBuilder getNoticeOrBuilder() {
    if (bodyCase_ == 4) {
       return (com.gomokumaster.proto.ServerNotice) body_;
    }
    return com.gomokumaster.proto.ServerNotice.getDefaultInstance();
  }

  public static final int CHATREQ_FIELD_NUMBER = 5;
  /**
   * <code>.com.gomokumaster.proto.ChatReq chatReq = 5;</code>
   */
  public com.gomokumaster.proto.ChatReq getChatReq() {
    if (bodyCase_ == 5) {
       return (com.gomokumaster.proto.ChatReq) body_;
    }
    return com.gomokumaster.proto.ChatReq.getDefaultInstance();
  }
  /**
   * <code>.com.gomokumaster.proto.ChatReq chatReq = 5;</code>
   */
  public com.gomokumaster.proto.ChatReqOrBuilder getChatReqOrBuilder() {
    if (bodyCase_ == 5) {
       return (com.gomokumaster.proto.ChatReq) body_;
    }
    return com.gomokumaster.proto.ChatReq.getDefaultInstance();
  }

  public static final int SURRENDER_FIELD_NUMBER = 6;
  /**
   * <code>.com.gomokumaster.proto.Surrender surrender = 6;</code>
   */
  public com.gomokumaster.proto.Surrender getSurrender() {
    if (bodyCase_ == 6) {
       return (com.gomokumaster.proto.Surrender) body_;
    }
    return com.gomokumaster.proto.Surrender.getDefaultInstance();
  }
  /**
   * <code>.com.gomokumaster.proto.Surrender surrender = 6;</code>
   */
  public com.gomokumaster.proto.SurrenderOrBuilder getSurrenderOrBuilder() {
    if (bodyCase_ == 6) {
       return (com.gomokumaster.proto.Surrender) body_;
    }
    return com.gomokumaster.proto.Surrender.getDefaultInstance();
  }

  public static final int WINNERID_FIELD_NUMBER = 7;
  /**
   * <pre>
   *胜者id
   * </pre>
   *
   * <code>string winnerId = 7;</code>
   */
  public java.lang.String getWinnerId() {
    java.lang.Object ref = "";
    if (bodyCase_ == 7) {
      ref = body_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bodyCase_ == 7) {
        body_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   *胜者id
   * </pre>
   *
   * <code>string winnerId = 7;</code>
   */
  public com.google.protobuf.ByteString
      getWinnerIdBytes() {
    java.lang.Object ref = "";
    if (bodyCase_ == 7) {
      ref = body_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (bodyCase_ == 7) {
        body_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TURNDEADLINE_FIELD_NUMBER = 10;
  /**
   * <pre>
   *每回合的时限
   * </pre>
   *
   * <code>int64 turnDeadline = 10;</code>
   */
  public long getTurnDeadline() {
    if (bodyCase_ == 10) {
      return (java.lang.Long) body_;
    }
    return 0L;
  }

  public static final int OPPONENTCOLOR_FIELD_NUMBER = 11;
  /**
   * <code>int32 opponentColor = 11;</code>
   */
  public int getOpponentColor() {
    if (bodyCase_ == 11) {
      return (java.lang.Integer) body_;
    }
    return 0;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.gomokumaster.proto.MsgType.UNKNOWN.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (bodyCase_ == 2) {
      output.writeMessage(2, (com.gomokumaster.proto.MoveReq) body_);
    }
    if (bodyCase_ == 3) {
      output.writeMessage(3, (com.gomokumaster.proto.GameSnapshot) body_);
    }
    if (bodyCase_ == 4) {
      output.writeMessage(4, (com.gomokumaster.proto.ServerNotice) body_);
    }
    if (bodyCase_ == 5) {
      output.writeMessage(5, (com.gomokumaster.proto.ChatReq) body_);
    }
    if (bodyCase_ == 6) {
      output.writeMessage(6, (com.gomokumaster.proto.Surrender) body_);
    }
    if (bodyCase_ == 7) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, body_);
    }
    if (bodyCase_ == 10) {
      output.writeInt64(
          10, (long)((java.lang.Long) body_));
    }
    if (bodyCase_ == 11) {
      output.writeInt32(
          11, (int)((java.lang.Integer) body_));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.gomokumaster.proto.MsgType.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (bodyCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.gomokumaster.proto.MoveReq) body_);
    }
    if (bodyCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.gomokumaster.proto.GameSnapshot) body_);
    }
    if (bodyCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.gomokumaster.proto.ServerNotice) body_);
    }
    if (bodyCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.gomokumaster.proto.ChatReq) body_);
    }
    if (bodyCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.gomokumaster.proto.Surrender) body_);
    }
    if (bodyCase_ == 7) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, body_);
    }
    if (bodyCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            10, (long)((java.lang.Long) body_));
    }
    if (bodyCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            11, (int)((java.lang.Integer) body_));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gomokumaster.proto.GamePacket)) {
      return super.equals(obj);
    }
    com.gomokumaster.proto.GamePacket other = (com.gomokumaster.proto.GamePacket) obj;

    boolean result = true;
    result = result && type_ == other.type_;
    result = result && getBodyCase().equals(
        other.getBodyCase());
    if (!result) return false;
    switch (bodyCase_) {
      case 2:
        result = result && getMoveReq()
            .equals(other.getMoveReq());
        break;
      case 3:
        result = result && getGameSnapshot()
            .equals(other.getGameSnapshot());
        break;
      case 4:
        result = result && getNotice()
            .equals(other.getNotice());
        break;
      case 5:
        result = result && getChatReq()
            .equals(other.getChatReq());
        break;
      case 6:
        result = result && getSurrender()
            .equals(other.getSurrender());
        break;
      case 7:
        result = result && getWinnerId()
            .equals(other.getWinnerId());
        break;
      case 10:
        result = result && (getTurnDeadline()
            == other.getTurnDeadline());
        break;
      case 11:
        result = result && (getOpponentColor()
            == other.getOpponentColor());
        break;
      case 0:
      default:
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    switch (bodyCase_) {
      case 2:
        hash = (37 * hash) + MOVEREQ_FIELD_NUMBER;
        hash = (53 * hash) + getMoveReq().hashCode();
        break;
      case 3:
        hash = (37 * hash) + GAMESNAPSHOT_FIELD_NUMBER;
        hash = (53 * hash) + getGameSnapshot().hashCode();
        break;
      case 4:
        hash = (37 * hash) + NOTICE_FIELD_NUMBER;
        hash = (53 * hash) + getNotice().hashCode();
        break;
      case 5:
        hash = (37 * hash) + CHATREQ_FIELD_NUMBER;
        hash = (53 * hash) + getChatReq().hashCode();
        break;
      case 6:
        hash = (37 * hash) + SURRENDER_FIELD_NUMBER;
        hash = (53 * hash) + getSurrender().hashCode();
        break;
      case 7:
        hash = (37 * hash) + WINNERID_FIELD_NUMBER;
        hash = (53 * hash) + getWinnerId().hashCode();
        break;
      case 10:
        hash = (37 * hash) + TURNDEADLINE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTurnDeadline());
        break;
      case 11:
        hash = (37 * hash) + OPPONENTCOLOR_FIELD_NUMBER;
        hash = (53 * hash) + getOpponentColor();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gomokumaster.proto.GamePacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gomokumaster.proto.GamePacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gomokumaster.proto.GamePacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gomokumaster.proto.GamePacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gomokumaster.proto.GamePacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.GamePacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gomokumaster.proto.GamePacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.GamePacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gomokumaster.proto.GamePacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.GamePacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gomokumaster.proto.GamePacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *前后端通信的消息包，包含消息类型和消息体
   * </pre>
   *
   * Protobuf type {@code com.gomokumaster.proto.GamePacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gomokumaster.proto.GamePacket)
      com.gomokumaster.proto.GamePacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_GamePacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_GamePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gomokumaster.proto.GamePacket.class, com.gomokumaster.proto.GamePacket.Builder.class);
    }

    // Construct using com.gomokumaster.proto.GamePacket.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      bodyCase_ = 0;
      body_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_GamePacket_descriptor;
    }

    public com.gomokumaster.proto.GamePacket getDefaultInstanceForType() {
      return com.gomokumaster.proto.GamePacket.getDefaultInstance();
    }

    public com.gomokumaster.proto.GamePacket build() {
      com.gomokumaster.proto.GamePacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.gomokumaster.proto.GamePacket buildPartial() {
      com.gomokumaster.proto.GamePacket result = new com.gomokumaster.proto.GamePacket(this);
      result.type_ = type_;
      if (bodyCase_ == 2) {
        if (moveReqBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = moveReqBuilder_.build();
        }
      }
      if (bodyCase_ == 3) {
        if (gameSnapshotBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = gameSnapshotBuilder_.build();
        }
      }
      if (bodyCase_ == 4) {
        if (noticeBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = noticeBuilder_.build();
        }
      }
      if (bodyCase_ == 5) {
        if (chatReqBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = chatReqBuilder_.build();
        }
      }
      if (bodyCase_ == 6) {
        if (surrenderBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = surrenderBuilder_.build();
        }
      }
      if (bodyCase_ == 7) {
        result.body_ = body_;
      }
      if (bodyCase_ == 10) {
        result.body_ = body_;
      }
      if (bodyCase_ == 11) {
        result.body_ = body_;
      }
      result.bodyCase_ = bodyCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gomokumaster.proto.GamePacket) {
        return mergeFrom((com.gomokumaster.proto.GamePacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gomokumaster.proto.GamePacket other) {
      if (other == com.gomokumaster.proto.GamePacket.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      switch (other.getBodyCase()) {
        case MOVEREQ: {
          mergeMoveReq(other.getMoveReq());
          break;
        }
        case GAMESNAPSHOT: {
          mergeGameSnapshot(other.getGameSnapshot());
          break;
        }
        case NOTICE: {
          mergeNotice(other.getNotice());
          break;
        }
        case CHATREQ: {
          mergeChatReq(other.getChatReq());
          break;
        }
        case SURRENDER: {
          mergeSurrender(other.getSurrender());
          break;
        }
        case WINNERID: {
          bodyCase_ = 7;
          body_ = other.body_;
          onChanged();
          break;
        }
        case TURNDEADLINE: {
          setTurnDeadline(other.getTurnDeadline());
          break;
        }
        case OPPONENTCOLOR: {
          setOpponentColor(other.getOpponentColor());
          break;
        }
        case BODY_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gomokumaster.proto.GamePacket parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gomokumaster.proto.GamePacket) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public BodyCase
        getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public Builder clearBody() {
      bodyCase_ = 0;
      body_ = null;
      onChanged();
      return this;
    }


    private int type_ = 0;
    /**
     * <code>.com.gomokumaster.proto.MsgType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.gomokumaster.proto.MsgType type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.MsgType type = 1;</code>
     */
    public com.gomokumaster.proto.MsgType getType() {
      com.gomokumaster.proto.MsgType result = com.gomokumaster.proto.MsgType.valueOf(type_);
      return result == null ? com.gomokumaster.proto.MsgType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.gomokumaster.proto.MsgType type = 1;</code>
     */
    public Builder setType(com.gomokumaster.proto.MsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.MsgType type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.MoveReq, com.gomokumaster.proto.MoveReq.Builder, com.gomokumaster.proto.MoveReqOrBuilder> moveReqBuilder_;
    /**
     * <code>.com.gomokumaster.proto.MoveReq moveReq = 2;</code>
     */
    public com.gomokumaster.proto.MoveReq getMoveReq() {
      if (moveReqBuilder_ == null) {
        if (bodyCase_ == 2) {
          return (com.gomokumaster.proto.MoveReq) body_;
        }
        return com.gomokumaster.proto.MoveReq.getDefaultInstance();
      } else {
        if (bodyCase_ == 2) {
          return moveReqBuilder_.getMessage();
        }
        return com.gomokumaster.proto.MoveReq.getDefaultInstance();
      }
    }
    /**
     * <code>.com.gomokumaster.proto.MoveReq moveReq = 2;</code>
     */
    public Builder setMoveReq(com.gomokumaster.proto.MoveReq value) {
      if (moveReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        moveReqBuilder_.setMessage(value);
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.MoveReq moveReq = 2;</code>
     */
    public Builder setMoveReq(
        com.gomokumaster.proto.MoveReq.Builder builderForValue) {
      if (moveReqBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        moveReqBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.MoveReq moveReq = 2;</code>
     */
    public Builder mergeMoveReq(com.gomokumaster.proto.MoveReq value) {
      if (moveReqBuilder_ == null) {
        if (bodyCase_ == 2 &&
            body_ != com.gomokumaster.proto.MoveReq.getDefaultInstance()) {
          body_ = com.gomokumaster.proto.MoveReq.newBuilder((com.gomokumaster.proto.MoveReq) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 2) {
          moveReqBuilder_.mergeFrom(value);
        }
        moveReqBuilder_.setMessage(value);
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.MoveReq moveReq = 2;</code>
     */
    public Builder clearMoveReq() {
      if (moveReqBuilder_ == null) {
        if (bodyCase_ == 2) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 2) {
          bodyCase_ = 0;
          body_ = null;
        }
        moveReqBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.MoveReq moveReq = 2;</code>
     */
    public com.gomokumaster.proto.MoveReq.Builder getMoveReqBuilder() {
      return getMoveReqFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.gomokumaster.proto.MoveReq moveReq = 2;</code>
     */
    public com.gomokumaster.proto.MoveReqOrBuilder getMoveReqOrBuilder() {
      if ((bodyCase_ == 2) && (moveReqBuilder_ != null)) {
        return moveReqBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 2) {
          return (com.gomokumaster.proto.MoveReq) body_;
        }
        return com.gomokumaster.proto.MoveReq.getDefaultInstance();
      }
    }
    /**
     * <code>.com.gomokumaster.proto.MoveReq moveReq = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.MoveReq, com.gomokumaster.proto.MoveReq.Builder, com.gomokumaster.proto.MoveReqOrBuilder> 
        getMoveReqFieldBuilder() {
      if (moveReqBuilder_ == null) {
        if (!(bodyCase_ == 2)) {
          body_ = com.gomokumaster.proto.MoveReq.getDefaultInstance();
        }
        moveReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gomokumaster.proto.MoveReq, com.gomokumaster.proto.MoveReq.Builder, com.gomokumaster.proto.MoveReqOrBuilder>(
                (com.gomokumaster.proto.MoveReq) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 2;
      onChanged();;
      return moveReqBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.GameSnapshot, com.gomokumaster.proto.GameSnapshot.Builder, com.gomokumaster.proto.GameSnapshotOrBuilder> gameSnapshotBuilder_;
    /**
     * <code>.com.gomokumaster.proto.GameSnapshot gameSnapshot = 3;</code>
     */
    public com.gomokumaster.proto.GameSnapshot getGameSnapshot() {
      if (gameSnapshotBuilder_ == null) {
        if (bodyCase_ == 3) {
          return (com.gomokumaster.proto.GameSnapshot) body_;
        }
        return com.gomokumaster.proto.GameSnapshot.getDefaultInstance();
      } else {
        if (bodyCase_ == 3) {
          return gameSnapshotBuilder_.getMessage();
        }
        return com.gomokumaster.proto.GameSnapshot.getDefaultInstance();
      }
    }
    /**
     * <code>.com.gomokumaster.proto.GameSnapshot gameSnapshot = 3;</code>
     */
    public Builder setGameSnapshot(com.gomokumaster.proto.GameSnapshot value) {
      if (gameSnapshotBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        gameSnapshotBuilder_.setMessage(value);
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.GameSnapshot gameSnapshot = 3;</code>
     */
    public Builder setGameSnapshot(
        com.gomokumaster.proto.GameSnapshot.Builder builderForValue) {
      if (gameSnapshotBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        gameSnapshotBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.GameSnapshot gameSnapshot = 3;</code>
     */
    public Builder mergeGameSnapshot(com.gomokumaster.proto.GameSnapshot value) {
      if (gameSnapshotBuilder_ == null) {
        if (bodyCase_ == 3 &&
            body_ != com.gomokumaster.proto.GameSnapshot.getDefaultInstance()) {
          body_ = com.gomokumaster.proto.GameSnapshot.newBuilder((com.gomokumaster.proto.GameSnapshot) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 3) {
          gameSnapshotBuilder_.mergeFrom(value);
        }
        gameSnapshotBuilder_.setMessage(value);
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.GameSnapshot gameSnapshot = 3;</code>
     */
    public Builder clearGameSnapshot() {
      if (gameSnapshotBuilder_ == null) {
        if (bodyCase_ == 3) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 3) {
          bodyCase_ = 0;
          body_ = null;
        }
        gameSnapshotBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.GameSnapshot gameSnapshot = 3;</code>
     */
    public com.gomokumaster.proto.GameSnapshot.Builder getGameSnapshotBuilder() {
      return getGameSnapshotFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.gomokumaster.proto.GameSnapshot gameSnapshot = 3;</code>
     */
    public com.gomokumaster.proto.GameSnapshotOrBuilder getGameSnapshotOrBuilder() {
      if ((bodyCase_ == 3) && (gameSnapshotBuilder_ != null)) {
        return gameSnapshotBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 3) {
          return (com.gomokumaster.proto.GameSnapshot) body_;
        }
        return com.gomokumaster.proto.GameSnapshot.getDefaultInstance();
      }
    }
    /**
     * <code>.com.gomokumaster.proto.GameSnapshot gameSnapshot = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.GameSnapshot, com.gomokumaster.proto.GameSnapshot.Builder, com.gomokumaster.proto.GameSnapshotOrBuilder> 
        getGameSnapshotFieldBuilder() {
      if (gameSnapshotBuilder_ == null) {
        if (!(bodyCase_ == 3)) {
          body_ = com.gomokumaster.proto.GameSnapshot.getDefaultInstance();
        }
        gameSnapshotBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gomokumaster.proto.GameSnapshot, com.gomokumaster.proto.GameSnapshot.Builder, com.gomokumaster.proto.GameSnapshotOrBuilder>(
                (com.gomokumaster.proto.GameSnapshot) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 3;
      onChanged();;
      return gameSnapshotBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.ServerNotice, com.gomokumaster.proto.ServerNotice.Builder, com.gomokumaster.proto.ServerNoticeOrBuilder> noticeBuilder_;
    /**
     * <code>.com.gomokumaster.proto.ServerNotice notice = 4;</code>
     */
    public com.gomokumaster.proto.ServerNotice getNotice() {
      if (noticeBuilder_ == null) {
        if (bodyCase_ == 4) {
          return (com.gomokumaster.proto.ServerNotice) body_;
        }
        return com.gomokumaster.proto.ServerNotice.getDefaultInstance();
      } else {
        if (bodyCase_ == 4) {
          return noticeBuilder_.getMessage();
        }
        return com.gomokumaster.proto.ServerNotice.getDefaultInstance();
      }
    }
    /**
     * <code>.com.gomokumaster.proto.ServerNotice notice = 4;</code>
     */
    public Builder setNotice(com.gomokumaster.proto.ServerNotice value) {
      if (noticeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        noticeBuilder_.setMessage(value);
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.ServerNotice notice = 4;</code>
     */
    public Builder setNotice(
        com.gomokumaster.proto.ServerNotice.Builder builderForValue) {
      if (noticeBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        noticeBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.ServerNotice notice = 4;</code>
     */
    public Builder mergeNotice(com.gomokumaster.proto.ServerNotice value) {
      if (noticeBuilder_ == null) {
        if (bodyCase_ == 4 &&
            body_ != com.gomokumaster.proto.ServerNotice.getDefaultInstance()) {
          body_ = com.gomokumaster.proto.ServerNotice.newBuilder((com.gomokumaster.proto.ServerNotice) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 4) {
          noticeBuilder_.mergeFrom(value);
        }
        noticeBuilder_.setMessage(value);
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.ServerNotice notice = 4;</code>
     */
    public Builder clearNotice() {
      if (noticeBuilder_ == null) {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
        }
        noticeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.ServerNotice notice = 4;</code>
     */
    public com.gomokumaster.proto.ServerNotice.Builder getNoticeBuilder() {
      return getNoticeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.gomokumaster.proto.ServerNotice notice = 4;</code>
     */
    public com.gomokumaster.proto.ServerNoticeOrBuilder getNoticeOrBuilder() {
      if ((bodyCase_ == 4) && (noticeBuilder_ != null)) {
        return noticeBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 4) {
          return (com.gomokumaster.proto.ServerNotice) body_;
        }
        return com.gomokumaster.proto.ServerNotice.getDefaultInstance();
      }
    }
    /**
     * <code>.com.gomokumaster.proto.ServerNotice notice = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.ServerNotice, com.gomokumaster.proto.ServerNotice.Builder, com.gomokumaster.proto.ServerNoticeOrBuilder> 
        getNoticeFieldBuilder() {
      if (noticeBuilder_ == null) {
        if (!(bodyCase_ == 4)) {
          body_ = com.gomokumaster.proto.ServerNotice.getDefaultInstance();
        }
        noticeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gomokumaster.proto.ServerNotice, com.gomokumaster.proto.ServerNotice.Builder, com.gomokumaster.proto.ServerNoticeOrBuilder>(
                (com.gomokumaster.proto.ServerNotice) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 4;
      onChanged();;
      return noticeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.ChatReq, com.gomokumaster.proto.ChatReq.Builder, com.gomokumaster.proto.ChatReqOrBuilder> chatReqBuilder_;
    /**
     * <code>.com.gomokumaster.proto.ChatReq chatReq = 5;</code>
     */
    public com.gomokumaster.proto.ChatReq getChatReq() {
      if (chatReqBuilder_ == null) {
        if (bodyCase_ == 5) {
          return (com.gomokumaster.proto.ChatReq) body_;
        }
        return com.gomokumaster.proto.ChatReq.getDefaultInstance();
      } else {
        if (bodyCase_ == 5) {
          return chatReqBuilder_.getMessage();
        }
        return com.gomokumaster.proto.ChatReq.getDefaultInstance();
      }
    }
    /**
     * <code>.com.gomokumaster.proto.ChatReq chatReq = 5;</code>
     */
    public Builder setChatReq(com.gomokumaster.proto.ChatReq value) {
      if (chatReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        chatReqBuilder_.setMessage(value);
      }
      bodyCase_ = 5;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.ChatReq chatReq = 5;</code>
     */
    public Builder setChatReq(
        com.gomokumaster.proto.ChatReq.Builder builderForValue) {
      if (chatReqBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        chatReqBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 5;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.ChatReq chatReq = 5;</code>
     */
    public Builder mergeChatReq(com.gomokumaster.proto.ChatReq value) {
      if (chatReqBuilder_ == null) {
        if (bodyCase_ == 5 &&
            body_ != com.gomokumaster.proto.ChatReq.getDefaultInstance()) {
          body_ = com.gomokumaster.proto.ChatReq.newBuilder((com.gomokumaster.proto.ChatReq) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 5) {
          chatReqBuilder_.mergeFrom(value);
        }
        chatReqBuilder_.setMessage(value);
      }
      bodyCase_ = 5;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.ChatReq chatReq = 5;</code>
     */
    public Builder clearChatReq() {
      if (chatReqBuilder_ == null) {
        if (bodyCase_ == 5) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 5) {
          bodyCase_ = 0;
          body_ = null;
        }
        chatReqBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.ChatReq chatReq = 5;</code>
     */
    public com.gomokumaster.proto.ChatReq.Builder getChatReqBuilder() {
      return getChatReqFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.gomokumaster.proto.ChatReq chatReq = 5;</code>
     */
    public com.gomokumaster.proto.ChatReqOrBuilder getChatReqOrBuilder() {
      if ((bodyCase_ == 5) && (chatReqBuilder_ != null)) {
        return chatReqBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 5) {
          return (com.gomokumaster.proto.ChatReq) body_;
        }
        return com.gomokumaster.proto.ChatReq.getDefaultInstance();
      }
    }
    /**
     * <code>.com.gomokumaster.proto.ChatReq chatReq = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.ChatReq, com.gomokumaster.proto.ChatReq.Builder, com.gomokumaster.proto.ChatReqOrBuilder> 
        getChatReqFieldBuilder() {
      if (chatReqBuilder_ == null) {
        if (!(bodyCase_ == 5)) {
          body_ = com.gomokumaster.proto.ChatReq.getDefaultInstance();
        }
        chatReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gomokumaster.proto.ChatReq, com.gomokumaster.proto.ChatReq.Builder, com.gomokumaster.proto.ChatReqOrBuilder>(
                (com.gomokumaster.proto.ChatReq) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 5;
      onChanged();;
      return chatReqBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.Surrender, com.gomokumaster.proto.Surrender.Builder, com.gomokumaster.proto.SurrenderOrBuilder> surrenderBuilder_;
    /**
     * <code>.com.gomokumaster.proto.Surrender surrender = 6;</code>
     */
    public com.gomokumaster.proto.Surrender getSurrender() {
      if (surrenderBuilder_ == null) {
        if (bodyCase_ == 6) {
          return (com.gomokumaster.proto.Surrender) body_;
        }
        return com.gomokumaster.proto.Surrender.getDefaultInstance();
      } else {
        if (bodyCase_ == 6) {
          return surrenderBuilder_.getMessage();
        }
        return com.gomokumaster.proto.Surrender.getDefaultInstance();
      }
    }
    /**
     * <code>.com.gomokumaster.proto.Surrender surrender = 6;</code>
     */
    public Builder setSurrender(com.gomokumaster.proto.Surrender value) {
      if (surrenderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        surrenderBuilder_.setMessage(value);
      }
      bodyCase_ = 6;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.Surrender surrender = 6;</code>
     */
    public Builder setSurrender(
        com.gomokumaster.proto.Surrender.Builder builderForValue) {
      if (surrenderBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        surrenderBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 6;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.Surrender surrender = 6;</code>
     */
    public Builder mergeSurrender(com.gomokumaster.proto.Surrender value) {
      if (surrenderBuilder_ == null) {
        if (bodyCase_ == 6 &&
            body_ != com.gomokumaster.proto.Surrender.getDefaultInstance()) {
          body_ = com.gomokumaster.proto.Surrender.newBuilder((com.gomokumaster.proto.Surrender) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 6) {
          surrenderBuilder_.mergeFrom(value);
        }
        surrenderBuilder_.setMessage(value);
      }
      bodyCase_ = 6;
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.Surrender surrender = 6;</code>
     */
    public Builder clearSurrender() {
      if (surrenderBuilder_ == null) {
        if (bodyCase_ == 6) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 6) {
          bodyCase_ = 0;
          body_ = null;
        }
        surrenderBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.Surrender surrender = 6;</code>
     */
    public com.gomokumaster.proto.Surrender.Builder getSurrenderBuilder() {
      return getSurrenderFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.gomokumaster.proto.Surrender surrender = 6;</code>
     */
    public com.gomokumaster.proto.SurrenderOrBuilder getSurrenderOrBuilder() {
      if ((bodyCase_ == 6) && (surrenderBuilder_ != null)) {
        return surrenderBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 6) {
          return (com.gomokumaster.proto.Surrender) body_;
        }
        return com.gomokumaster.proto.Surrender.getDefaultInstance();
      }
    }
    /**
     * <code>.com.gomokumaster.proto.Surrender surrender = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gomokumaster.proto.Surrender, com.gomokumaster.proto.Surrender.Builder, com.gomokumaster.proto.SurrenderOrBuilder> 
        getSurrenderFieldBuilder() {
      if (surrenderBuilder_ == null) {
        if (!(bodyCase_ == 6)) {
          body_ = com.gomokumaster.proto.Surrender.getDefaultInstance();
        }
        surrenderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gomokumaster.proto.Surrender, com.gomokumaster.proto.Surrender.Builder, com.gomokumaster.proto.SurrenderOrBuilder>(
                (com.gomokumaster.proto.Surrender) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 6;
      onChanged();;
      return surrenderBuilder_;
    }

    /**
     * <pre>
     *胜者id
     * </pre>
     *
     * <code>string winnerId = 7;</code>
     */
    public java.lang.String getWinnerId() {
      java.lang.Object ref = "";
      if (bodyCase_ == 7) {
        ref = body_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bodyCase_ == 7) {
          body_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *胜者id
     * </pre>
     *
     * <code>string winnerId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getWinnerIdBytes() {
      java.lang.Object ref = "";
      if (bodyCase_ == 7) {
        ref = body_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (bodyCase_ == 7) {
          body_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *胜者id
     * </pre>
     *
     * <code>string winnerId = 7;</code>
     */
    public Builder setWinnerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 7;
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *胜者id
     * </pre>
     *
     * <code>string winnerId = 7;</code>
     */
    public Builder clearWinnerId() {
      if (bodyCase_ == 7) {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     *胜者id
     * </pre>
     *
     * <code>string winnerId = 7;</code>
     */
    public Builder setWinnerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bodyCase_ = 7;
      body_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     *每回合的时限
     * </pre>
     *
     * <code>int64 turnDeadline = 10;</code>
     */
    public long getTurnDeadline() {
      if (bodyCase_ == 10) {
        return (java.lang.Long) body_;
      }
      return 0L;
    }
    /**
     * <pre>
     *每回合的时限
     * </pre>
     *
     * <code>int64 turnDeadline = 10;</code>
     */
    public Builder setTurnDeadline(long value) {
      bodyCase_ = 10;
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *每回合的时限
     * </pre>
     *
     * <code>int64 turnDeadline = 10;</code>
     */
    public Builder clearTurnDeadline() {
      if (bodyCase_ == 10) {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>int32 opponentColor = 11;</code>
     */
    public int getOpponentColor() {
      if (bodyCase_ == 11) {
        return (java.lang.Integer) body_;
      }
      return 0;
    }
    /**
     * <code>int32 opponentColor = 11;</code>
     */
    public Builder setOpponentColor(int value) {
      bodyCase_ = 11;
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 opponentColor = 11;</code>
     */
    public Builder clearOpponentColor() {
      if (bodyCase_ == 11) {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
      }
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.gomokumaster.proto.GamePacket)
  }

  // @@protoc_insertion_point(class_scope:com.gomokumaster.proto.GamePacket)
  private static final com.gomokumaster.proto.GamePacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gomokumaster.proto.GamePacket();
  }

  public static com.gomokumaster.proto.GamePacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GamePacket>
      PARSER = new com.google.protobuf.AbstractParser<GamePacket>() {
    public GamePacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GamePacket(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GamePacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GamePacket> getParserForType() {
    return PARSER;
  }

  public com.gomokumaster.proto.GamePacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

