// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

public interface GamePacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gomokumaster.proto.GamePacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.gomokumaster.proto.MsgType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.com.gomokumaster.proto.MsgType type = 1;</code>
   */
  com.gomokumaster.proto.MsgType getType();

  /**
   * <code>.com.gomokumaster.proto.MoveReq moveReq = 2;</code>
   */
  com.gomokumaster.proto.MoveReq getMoveReq();
  /**
   * <code>.com.gomokumaster.proto.MoveReq moveReq = 2;</code>
   */
  com.gomokumaster.proto.MoveReqOrBuilder getMoveReqOrBuilder();

  /**
   * <code>.com.gomokumaster.proto.GameSnapshot gameSnapshot = 3;</code>
   */
  com.gomokumaster.proto.GameSnapshot getGameSnapshot();
  /**
   * <code>.com.gomokumaster.proto.GameSnapshot gameSnapshot = 3;</code>
   */
  com.gomokumaster.proto.GameSnapshotOrBuilder getGameSnapshotOrBuilder();

  /**
   * <code>.com.gomokumaster.proto.ServerNotice notice = 4;</code>
   */
  com.gomokumaster.proto.ServerNotice getNotice();
  /**
   * <code>.com.gomokumaster.proto.ServerNotice notice = 4;</code>
   */
  com.gomokumaster.proto.ServerNoticeOrBuilder getNoticeOrBuilder();

  /**
   * <code>.com.gomokumaster.proto.ChatReq chatReq = 5;</code>
   */
  com.gomokumaster.proto.ChatReq getChatReq();
  /**
   * <code>.com.gomokumaster.proto.ChatReq chatReq = 5;</code>
   */
  com.gomokumaster.proto.ChatReqOrBuilder getChatReqOrBuilder();

  /**
   * <code>.com.gomokumaster.proto.Surrender surrender = 6;</code>
   */
  com.gomokumaster.proto.Surrender getSurrender();
  /**
   * <code>.com.gomokumaster.proto.Surrender surrender = 6;</code>
   */
  com.gomokumaster.proto.SurrenderOrBuilder getSurrenderOrBuilder();

  /**
   * <pre>
   *胜者id
   * </pre>
   *
   * <code>string winnerId = 7;</code>
   */
  java.lang.String getWinnerId();
  /**
   * <pre>
   *胜者id
   * </pre>
   *
   * <code>string winnerId = 7;</code>
   */
  com.google.protobuf.ByteString
      getWinnerIdBytes();

  /**
   * <pre>
   *每回合的时限
   * </pre>
   *
   * <code>int64 turnDeadline = 10;</code>
   */
  long getTurnDeadline();

  /**
   * <code>int32 opponentColor = 11;</code>
   */
  int getOpponentColor();

  public com.gomokumaster.proto.GamePacket.BodyCase getBodyCase();
}
