// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

/**
 * <pre>
 *落子请求
 * </pre>
 *
 * Protobuf type {@code com.gomokumaster.proto.MoveReq}
 */
public  final class MoveReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gomokumaster.proto.MoveReq)
    MoveReqOrBuilder {
  // Use MoveReq.newBuilder() to construct.
  private MoveReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MoveReq() {
    x_ = 0;
    y_ = 0;
    pieceType_ = "";
    type_ = 0;
    targetX_ = 0;
    targetY_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MoveReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            x_ = input.readInt32();
            break;
          }
          case 16: {

            y_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            pieceType_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 40: {

            targetX_ = input.readInt32();
            break;
          }
          case 48: {

            targetY_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_MoveReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_MoveReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gomokumaster.proto.MoveReq.class, com.gomokumaster.proto.MoveReq.Builder.class);
  }

  public static final int X_FIELD_NUMBER = 1;
  private int x_;
  /**
   * <code>int32 x = 1;</code>
   */
  public int getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 2;
  private int y_;
  /**
   * <code>int32 y = 2;</code>
   */
  public int getY() {
    return y_;
  }

  public static final int PIECETYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object pieceType_;
  /**
   * <code>string pieceType = 3;</code>
   */
  public java.lang.String getPieceType() {
    java.lang.Object ref = pieceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pieceType_ = s;
      return s;
    }
  }
  /**
   * <code>string pieceType = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPieceTypeBytes() {
    java.lang.Object ref = pieceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pieceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private int type_;
  /**
   * <code>.com.gomokumaster.proto.PlayAction type = 4;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.com.gomokumaster.proto.PlayAction type = 4;</code>
   */
  public com.gomokumaster.proto.PlayAction getType() {
    com.gomokumaster.proto.PlayAction result = com.gomokumaster.proto.PlayAction.valueOf(type_);
    return result == null ? com.gomokumaster.proto.PlayAction.UNRECOGNIZED : result;
  }

  public static final int TARGETX_FIELD_NUMBER = 5;
  private int targetX_;
  /**
   * <code>int32 targetX = 5;</code>
   */
  public int getTargetX() {
    return targetX_;
  }

  public static final int TARGETY_FIELD_NUMBER = 6;
  private int targetY_;
  /**
   * <code>int32 targetY = 6;</code>
   */
  public int getTargetY() {
    return targetY_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (x_ != 0) {
      output.writeInt32(1, x_);
    }
    if (y_ != 0) {
      output.writeInt32(2, y_);
    }
    if (!getPieceTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pieceType_);
    }
    if (type_ != com.gomokumaster.proto.PlayAction.NONE.getNumber()) {
      output.writeEnum(4, type_);
    }
    if (targetX_ != 0) {
      output.writeInt32(5, targetX_);
    }
    if (targetY_ != 0) {
      output.writeInt32(6, targetY_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (x_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, x_);
    }
    if (y_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, y_);
    }
    if (!getPieceTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pieceType_);
    }
    if (type_ != com.gomokumaster.proto.PlayAction.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, type_);
    }
    if (targetX_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, targetX_);
    }
    if (targetY_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, targetY_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gomokumaster.proto.MoveReq)) {
      return super.equals(obj);
    }
    com.gomokumaster.proto.MoveReq other = (com.gomokumaster.proto.MoveReq) obj;

    boolean result = true;
    result = result && (getX()
        == other.getX());
    result = result && (getY()
        == other.getY());
    result = result && getPieceType()
        .equals(other.getPieceType());
    result = result && type_ == other.type_;
    result = result && (getTargetX()
        == other.getTargetX());
    result = result && (getTargetY()
        == other.getTargetY());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + getX();
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + getY();
    hash = (37 * hash) + PIECETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPieceType().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + TARGETX_FIELD_NUMBER;
    hash = (53 * hash) + getTargetX();
    hash = (37 * hash) + TARGETY_FIELD_NUMBER;
    hash = (53 * hash) + getTargetY();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gomokumaster.proto.MoveReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gomokumaster.proto.MoveReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gomokumaster.proto.MoveReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gomokumaster.proto.MoveReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gomokumaster.proto.MoveReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.MoveReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gomokumaster.proto.MoveReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.MoveReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gomokumaster.proto.MoveReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.MoveReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gomokumaster.proto.MoveReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *落子请求
   * </pre>
   *
   * Protobuf type {@code com.gomokumaster.proto.MoveReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gomokumaster.proto.MoveReq)
      com.gomokumaster.proto.MoveReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_MoveReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_MoveReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gomokumaster.proto.MoveReq.class, com.gomokumaster.proto.MoveReq.Builder.class);
    }

    // Construct using com.gomokumaster.proto.MoveReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      x_ = 0;

      y_ = 0;

      pieceType_ = "";

      type_ = 0;

      targetX_ = 0;

      targetY_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_MoveReq_descriptor;
    }

    public com.gomokumaster.proto.MoveReq getDefaultInstanceForType() {
      return com.gomokumaster.proto.MoveReq.getDefaultInstance();
    }

    public com.gomokumaster.proto.MoveReq build() {
      com.gomokumaster.proto.MoveReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.gomokumaster.proto.MoveReq buildPartial() {
      com.gomokumaster.proto.MoveReq result = new com.gomokumaster.proto.MoveReq(this);
      result.x_ = x_;
      result.y_ = y_;
      result.pieceType_ = pieceType_;
      result.type_ = type_;
      result.targetX_ = targetX_;
      result.targetY_ = targetY_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gomokumaster.proto.MoveReq) {
        return mergeFrom((com.gomokumaster.proto.MoveReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gomokumaster.proto.MoveReq other) {
      if (other == com.gomokumaster.proto.MoveReq.getDefaultInstance()) return this;
      if (other.getX() != 0) {
        setX(other.getX());
      }
      if (other.getY() != 0) {
        setY(other.getY());
      }
      if (!other.getPieceType().isEmpty()) {
        pieceType_ = other.pieceType_;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getTargetX() != 0) {
        setTargetX(other.getTargetX());
      }
      if (other.getTargetY() != 0) {
        setTargetY(other.getTargetY());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gomokumaster.proto.MoveReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gomokumaster.proto.MoveReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int x_ ;
    /**
     * <code>int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }
    /**
     * <code>int32 x = 1;</code>
     */
    public Builder setX(int value) {
      
      x_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 x = 1;</code>
     */
    public Builder clearX() {
      
      x_ = 0;
      onChanged();
      return this;
    }

    private int y_ ;
    /**
     * <code>int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }
    /**
     * <code>int32 y = 2;</code>
     */
    public Builder setY(int value) {
      
      y_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 y = 2;</code>
     */
    public Builder clearY() {
      
      y_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object pieceType_ = "";
    /**
     * <code>string pieceType = 3;</code>
     */
    public java.lang.String getPieceType() {
      java.lang.Object ref = pieceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pieceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pieceType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPieceTypeBytes() {
      java.lang.Object ref = pieceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pieceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pieceType = 3;</code>
     */
    public Builder setPieceType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pieceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pieceType = 3;</code>
     */
    public Builder clearPieceType() {
      
      pieceType_ = getDefaultInstance().getPieceType();
      onChanged();
      return this;
    }
    /**
     * <code>string pieceType = 3;</code>
     */
    public Builder setPieceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pieceType_ = value;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.com.gomokumaster.proto.PlayAction type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.gomokumaster.proto.PlayAction type = 4;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.PlayAction type = 4;</code>
     */
    public com.gomokumaster.proto.PlayAction getType() {
      com.gomokumaster.proto.PlayAction result = com.gomokumaster.proto.PlayAction.valueOf(type_);
      return result == null ? com.gomokumaster.proto.PlayAction.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.gomokumaster.proto.PlayAction type = 4;</code>
     */
    public Builder setType(com.gomokumaster.proto.PlayAction value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.PlayAction type = 4;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int targetX_ ;
    /**
     * <code>int32 targetX = 5;</code>
     */
    public int getTargetX() {
      return targetX_;
    }
    /**
     * <code>int32 targetX = 5;</code>
     */
    public Builder setTargetX(int value) {
      
      targetX_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 targetX = 5;</code>
     */
    public Builder clearTargetX() {
      
      targetX_ = 0;
      onChanged();
      return this;
    }

    private int targetY_ ;
    /**
     * <code>int32 targetY = 6;</code>
     */
    public int getTargetY() {
      return targetY_;
    }
    /**
     * <code>int32 targetY = 6;</code>
     */
    public Builder setTargetY(int value) {
      
      targetY_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 targetY = 6;</code>
     */
    public Builder clearTargetY() {
      
      targetY_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.gomokumaster.proto.MoveReq)
  }

  // @@protoc_insertion_point(class_scope:com.gomokumaster.proto.MoveReq)
  private static final com.gomokumaster.proto.MoveReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gomokumaster.proto.MoveReq();
  }

  public static com.gomokumaster.proto.MoveReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MoveReq>
      PARSER = new com.google.protobuf.AbstractParser<MoveReq>() {
    public MoveReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MoveReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MoveReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MoveReq> getParserForType() {
    return PARSER;
  }

  public com.gomokumaster.proto.MoveReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

