// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

public interface MoveReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gomokumaster.proto.MoveReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   */
  int getY();

  /**
   * <code>string pieceType = 3;</code>
   */
  java.lang.String getPieceType();
  /**
   * <code>string pieceType = 3;</code>
   */
  com.google.protobuf.ByteString
      getPieceTypeBytes();

  /**
   * <code>.com.gomokumaster.proto.PlayAction type = 4;</code>
   */
  int getTypeValue();
  /**
   * <code>.com.gomokumaster.proto.PlayAction type = 4;</code>
   */
  com.gomokumaster.proto.PlayAction getType();

  /**
   * <code>int32 targetX = 5;</code>
   */
  int getTargetX();

  /**
   * <code>int32 targetY = 6;</code>
   */
  int getTargetY();
}
