// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

/**
 * <pre>
 *消息类型枚举（路由分发，前后端遵守）
 * </pre>
 *
 * Protobuf enum {@code com.gomokumaster.proto.MsgType}
 */
public enum MsgType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <pre>
   * 客户端请求匹配
   * </pre>
   *
   * <code>MATCH_REQ = 1001;</code>
   */
  MATCH_REQ(1001),
  /**
   * <pre>
   * 客户端取消匹配
   * </pre>
   *
   * <code>MATCH_CANCEL = 1002;</code>
   */
  MATCH_CANCEL(1002),
  /**
   * <pre>
   * 服务端响应匹配成功
   * </pre>
   *
   * <code>MATCH_RES = 1003;</code>
   */
  MATCH_RES(1003),
  /**
   * <pre>
   * 客户端请求落子/技能
   * </pre>
   *
   * <code>MOVE_REQ = 1004;</code>
   */
  MOVE_REQ(1004),
  /**
   * <pre>
   * 服务端广播棋盘更新
   * </pre>
   *
   * <code>BOARD_UPDATE = 1005;</code>
   */
  BOARD_UPDATE(1005),
  /**
   * <pre>
   * 游戏结束
   * </pre>
   *
   * <code>GAME_OVER = 1006;</code>
   */
  GAME_OVER(1006),
  /**
   * <pre>
   * 聊天请求
   * </pre>
   *
   * <code>CHAT_REQ = 1007;</code>
   */
  CHAT_REQ(1007),
  /**
   * <pre>
   * 聊天广播
   * </pre>
   *
   * <code>CHAT_RES = 1008;</code>
   */
  CHAT_RES(1008),
  /**
   * <pre>
   * 错误消息
   * </pre>
   *
   * <code>ERROR = 1009;</code>
   */
  ERROR(1009),
  /**
   * <pre>
   * 用户投降
   * </pre>
   *
   * <code>SURRENDER = 1011;</code>
   */
  SURRENDER(1011),
  /**
   * <pre>
   * 用户重连、上线
   * </pre>
   *
   * <code>CONNECT = 1012;</code>
   */
  CONNECT(1012),
  /**
   * <pre>
   * 游戏恢复
   * </pre>
   *
   * <code>GAME_RESUME = 1013;</code>
   */
  GAME_RESUME(1013),
  /**
   * <pre>
   * 心跳包
   * </pre>
   *
   * <code>HEARTBEAT = 1014;</code>
   */
  HEARTBEAT(1014),
  /**
   * <pre>
   * 用户掉线
   * </pre>
   *
   * <code>GAME_DISCONNECT = 1015;</code>
   */
  GAME_DISCONNECT(1015),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <pre>
   * 客户端请求匹配
   * </pre>
   *
   * <code>MATCH_REQ = 1001;</code>
   */
  public static final int MATCH_REQ_VALUE = 1001;
  /**
   * <pre>
   * 客户端取消匹配
   * </pre>
   *
   * <code>MATCH_CANCEL = 1002;</code>
   */
  public static final int MATCH_CANCEL_VALUE = 1002;
  /**
   * <pre>
   * 服务端响应匹配成功
   * </pre>
   *
   * <code>MATCH_RES = 1003;</code>
   */
  public static final int MATCH_RES_VALUE = 1003;
  /**
   * <pre>
   * 客户端请求落子/技能
   * </pre>
   *
   * <code>MOVE_REQ = 1004;</code>
   */
  public static final int MOVE_REQ_VALUE = 1004;
  /**
   * <pre>
   * 服务端广播棋盘更新
   * </pre>
   *
   * <code>BOARD_UPDATE = 1005;</code>
   */
  public static final int BOARD_UPDATE_VALUE = 1005;
  /**
   * <pre>
   * 游戏结束
   * </pre>
   *
   * <code>GAME_OVER = 1006;</code>
   */
  public static final int GAME_OVER_VALUE = 1006;
  /**
   * <pre>
   * 聊天请求
   * </pre>
   *
   * <code>CHAT_REQ = 1007;</code>
   */
  public static final int CHAT_REQ_VALUE = 1007;
  /**
   * <pre>
   * 聊天广播
   * </pre>
   *
   * <code>CHAT_RES = 1008;</code>
   */
  public static final int CHAT_RES_VALUE = 1008;
  /**
   * <pre>
   * 错误消息
   * </pre>
   *
   * <code>ERROR = 1009;</code>
   */
  public static final int ERROR_VALUE = 1009;
  /**
   * <pre>
   * 用户投降
   * </pre>
   *
   * <code>SURRENDER = 1011;</code>
   */
  public static final int SURRENDER_VALUE = 1011;
  /**
   * <pre>
   * 用户重连、上线
   * </pre>
   *
   * <code>CONNECT = 1012;</code>
   */
  public static final int CONNECT_VALUE = 1012;
  /**
   * <pre>
   * 游戏恢复
   * </pre>
   *
   * <code>GAME_RESUME = 1013;</code>
   */
  public static final int GAME_RESUME_VALUE = 1013;
  /**
   * <pre>
   * 心跳包
   * </pre>
   *
   * <code>HEARTBEAT = 1014;</code>
   */
  public static final int HEARTBEAT_VALUE = 1014;
  /**
   * <pre>
   * 用户掉线
   * </pre>
   *
   * <code>GAME_DISCONNECT = 1015;</code>
   */
  public static final int GAME_DISCONNECT_VALUE = 1015;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MsgType valueOf(int value) {
    return forNumber(value);
  }

  public static MsgType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1001: return MATCH_REQ;
      case 1002: return MATCH_CANCEL;
      case 1003: return MATCH_RES;
      case 1004: return MOVE_REQ;
      case 1005: return BOARD_UPDATE;
      case 1006: return GAME_OVER;
      case 1007: return CHAT_REQ;
      case 1008: return CHAT_RES;
      case 1009: return ERROR;
      case 1011: return SURRENDER;
      case 1012: return CONNECT;
      case 1013: return GAME_RESUME;
      case 1014: return HEARTBEAT;
      case 1015: return GAME_DISCONNECT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MsgType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
          public MsgType findValueByNumber(int number) {
            return MsgType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.gomokumaster.proto.GameMsgProtocol.getDescriptor().getEnumTypes().get(0);
  }

  private static final MsgType[] VALUES = values();

  public static MsgType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MsgType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.gomokumaster.proto.MsgType)
}

