// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

/**
 * Protobuf enum {@code com.gomokumaster.proto.PieceType}
 */
public enum PieceType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>EMPTY = 0;</code>
   */
  EMPTY(0),
  /**
   * <code>NORMAL = 1;</code>
   */
  NORMAL(1),
  /**
   * <code>ARCHER = 2;</code>
   */
  ARCHER(2),
  /**
   * <code>CAVALRY = 3;</code>
   */
  CAVALRY(3),
  /**
   * <code>SHIELD = 4;</code>
   */
  SHIELD(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>EMPTY = 0;</code>
   */
  public static final int EMPTY_VALUE = 0;
  /**
   * <code>NORMAL = 1;</code>
   */
  public static final int NORMAL_VALUE = 1;
  /**
   * <code>ARCHER = 2;</code>
   */
  public static final int ARCHER_VALUE = 2;
  /**
   * <code>CAVALRY = 3;</code>
   */
  public static final int CAVALRY_VALUE = 3;
  /**
   * <code>SHIELD = 4;</code>
   */
  public static final int SHIELD_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PieceType valueOf(int value) {
    return forNumber(value);
  }

  public static PieceType forNumber(int value) {
    switch (value) {
      case 0: return EMPTY;
      case 1: return NORMAL;
      case 2: return ARCHER;
      case 3: return CAVALRY;
      case 4: return SHIELD;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PieceType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PieceType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PieceType>() {
          public PieceType findValueByNumber(int number) {
            return PieceType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.gomokumaster.proto.GameMsgProtocol.getDescriptor().getEnumTypes().get(2);
  }

  private static final PieceType[] VALUES = values();

  public static PieceType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PieceType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.gomokumaster.proto.PieceType)
}

