// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

/**
 * Protobuf type {@code com.gomokumaster.proto.Piece}
 */
public  final class Piece extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gomokumaster.proto.Piece)
    PieceOrBuilder {
  // Use Piece.newBuilder() to construct.
  private Piece(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Piece() {
    id_ = "";
    x_ = 0;
    y_ = 0;
    ownerId_ = "";
    pieceType_ = 0;
    maxCd_ = 0;
    color_ = 0;
    isAlive_ = false;
    skillCd_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Piece(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 16: {

            x_ = input.readInt32();
            break;
          }
          case 24: {

            y_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            ownerId_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            pieceType_ = rawValue;
            break;
          }
          case 56: {

            maxCd_ = input.readInt32();
            break;
          }
          case 64: {

            color_ = input.readInt32();
            break;
          }
          case 72: {

            isAlive_ = input.readBool();
            break;
          }
          case 88: {

            skillCd_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_Piece_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_Piece_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gomokumaster.proto.Piece.class, com.gomokumaster.proto.Piece.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int X_FIELD_NUMBER = 2;
  private int x_;
  /**
   * <code>int32 x = 2;</code>
   */
  public int getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 3;
  private int y_;
  /**
   * <code>int32 y = 3;</code>
   */
  public int getY() {
    return y_;
  }

  public static final int OWNERID_FIELD_NUMBER = 5;
  private volatile java.lang.Object ownerId_;
  /**
   * <code>string ownerId = 5;</code>
   */
  public java.lang.String getOwnerId() {
    java.lang.Object ref = ownerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ownerId_ = s;
      return s;
    }
  }
  /**
   * <code>string ownerId = 5;</code>
   */
  public com.google.protobuf.ByteString
      getOwnerIdBytes() {
    java.lang.Object ref = ownerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ownerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PIECETYPE_FIELD_NUMBER = 6;
  private int pieceType_;
  /**
   * <code>.com.gomokumaster.proto.PieceType pieceType = 6;</code>
   */
  public int getPieceTypeValue() {
    return pieceType_;
  }
  /**
   * <code>.com.gomokumaster.proto.PieceType pieceType = 6;</code>
   */
  public com.gomokumaster.proto.PieceType getPieceType() {
    com.gomokumaster.proto.PieceType result = com.gomokumaster.proto.PieceType.valueOf(pieceType_);
    return result == null ? com.gomokumaster.proto.PieceType.UNRECOGNIZED : result;
  }

  public static final int MAXCD_FIELD_NUMBER = 7;
  private int maxCd_;
  /**
   * <code>int32 maxCd = 7;</code>
   */
  public int getMaxCd() {
    return maxCd_;
  }

  public static final int COLOR_FIELD_NUMBER = 8;
  private int color_;
  /**
   * <code>int32 color = 8;</code>
   */
  public int getColor() {
    return color_;
  }

  public static final int ISALIVE_FIELD_NUMBER = 9;
  private boolean isAlive_;
  /**
   * <code>bool isAlive = 9;</code>
   */
  public boolean getIsAlive() {
    return isAlive_;
  }

  public static final int SKILLCD_FIELD_NUMBER = 11;
  private int skillCd_;
  /**
   * <code>int32 skillCd = 11;</code>
   */
  public int getSkillCd() {
    return skillCd_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (x_ != 0) {
      output.writeInt32(2, x_);
    }
    if (y_ != 0) {
      output.writeInt32(3, y_);
    }
    if (!getOwnerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ownerId_);
    }
    if (pieceType_ != com.gomokumaster.proto.PieceType.EMPTY.getNumber()) {
      output.writeEnum(6, pieceType_);
    }
    if (maxCd_ != 0) {
      output.writeInt32(7, maxCd_);
    }
    if (color_ != 0) {
      output.writeInt32(8, color_);
    }
    if (isAlive_ != false) {
      output.writeBool(9, isAlive_);
    }
    if (skillCd_ != 0) {
      output.writeInt32(11, skillCd_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (x_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, x_);
    }
    if (y_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, y_);
    }
    if (!getOwnerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, ownerId_);
    }
    if (pieceType_ != com.gomokumaster.proto.PieceType.EMPTY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, pieceType_);
    }
    if (maxCd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, maxCd_);
    }
    if (color_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, color_);
    }
    if (isAlive_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, isAlive_);
    }
    if (skillCd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, skillCd_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gomokumaster.proto.Piece)) {
      return super.equals(obj);
    }
    com.gomokumaster.proto.Piece other = (com.gomokumaster.proto.Piece) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && (getX()
        == other.getX());
    result = result && (getY()
        == other.getY());
    result = result && getOwnerId()
        .equals(other.getOwnerId());
    result = result && pieceType_ == other.pieceType_;
    result = result && (getMaxCd()
        == other.getMaxCd());
    result = result && (getColor()
        == other.getColor());
    result = result && (getIsAlive()
        == other.getIsAlive());
    result = result && (getSkillCd()
        == other.getSkillCd());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + getX();
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + getY();
    hash = (37 * hash) + OWNERID_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerId().hashCode();
    hash = (37 * hash) + PIECETYPE_FIELD_NUMBER;
    hash = (53 * hash) + pieceType_;
    hash = (37 * hash) + MAXCD_FIELD_NUMBER;
    hash = (53 * hash) + getMaxCd();
    hash = (37 * hash) + COLOR_FIELD_NUMBER;
    hash = (53 * hash) + getColor();
    hash = (37 * hash) + ISALIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsAlive());
    hash = (37 * hash) + SKILLCD_FIELD_NUMBER;
    hash = (53 * hash) + getSkillCd();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gomokumaster.proto.Piece parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gomokumaster.proto.Piece parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gomokumaster.proto.Piece parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gomokumaster.proto.Piece parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gomokumaster.proto.Piece parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.Piece parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gomokumaster.proto.Piece parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.Piece parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gomokumaster.proto.Piece parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.Piece parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gomokumaster.proto.Piece prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gomokumaster.proto.Piece}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gomokumaster.proto.Piece)
      com.gomokumaster.proto.PieceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_Piece_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_Piece_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gomokumaster.proto.Piece.class, com.gomokumaster.proto.Piece.Builder.class);
    }

    // Construct using com.gomokumaster.proto.Piece.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = "";

      x_ = 0;

      y_ = 0;

      ownerId_ = "";

      pieceType_ = 0;

      maxCd_ = 0;

      color_ = 0;

      isAlive_ = false;

      skillCd_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_Piece_descriptor;
    }

    public com.gomokumaster.proto.Piece getDefaultInstanceForType() {
      return com.gomokumaster.proto.Piece.getDefaultInstance();
    }

    public com.gomokumaster.proto.Piece build() {
      com.gomokumaster.proto.Piece result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.gomokumaster.proto.Piece buildPartial() {
      com.gomokumaster.proto.Piece result = new com.gomokumaster.proto.Piece(this);
      result.id_ = id_;
      result.x_ = x_;
      result.y_ = y_;
      result.ownerId_ = ownerId_;
      result.pieceType_ = pieceType_;
      result.maxCd_ = maxCd_;
      result.color_ = color_;
      result.isAlive_ = isAlive_;
      result.skillCd_ = skillCd_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gomokumaster.proto.Piece) {
        return mergeFrom((com.gomokumaster.proto.Piece)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gomokumaster.proto.Piece other) {
      if (other == com.gomokumaster.proto.Piece.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.getX() != 0) {
        setX(other.getX());
      }
      if (other.getY() != 0) {
        setY(other.getY());
      }
      if (!other.getOwnerId().isEmpty()) {
        ownerId_ = other.ownerId_;
        onChanged();
      }
      if (other.pieceType_ != 0) {
        setPieceTypeValue(other.getPieceTypeValue());
      }
      if (other.getMaxCd() != 0) {
        setMaxCd(other.getMaxCd());
      }
      if (other.getColor() != 0) {
        setColor(other.getColor());
      }
      if (other.getIsAlive() != false) {
        setIsAlive(other.getIsAlive());
      }
      if (other.getSkillCd() != 0) {
        setSkillCd(other.getSkillCd());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gomokumaster.proto.Piece parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gomokumaster.proto.Piece) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private int x_ ;
    /**
     * <code>int32 x = 2;</code>
     */
    public int getX() {
      return x_;
    }
    /**
     * <code>int32 x = 2;</code>
     */
    public Builder setX(int value) {
      
      x_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 x = 2;</code>
     */
    public Builder clearX() {
      
      x_ = 0;
      onChanged();
      return this;
    }

    private int y_ ;
    /**
     * <code>int32 y = 3;</code>
     */
    public int getY() {
      return y_;
    }
    /**
     * <code>int32 y = 3;</code>
     */
    public Builder setY(int value) {
      
      y_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 y = 3;</code>
     */
    public Builder clearY() {
      
      y_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object ownerId_ = "";
    /**
     * <code>string ownerId = 5;</code>
     */
    public java.lang.String getOwnerId() {
      java.lang.Object ref = ownerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ownerId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOwnerIdBytes() {
      java.lang.Object ref = ownerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ownerId = 5;</code>
     */
    public Builder setOwnerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ownerId = 5;</code>
     */
    public Builder clearOwnerId() {
      
      ownerId_ = getDefaultInstance().getOwnerId();
      onChanged();
      return this;
    }
    /**
     * <code>string ownerId = 5;</code>
     */
    public Builder setOwnerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ownerId_ = value;
      onChanged();
      return this;
    }

    private int pieceType_ = 0;
    /**
     * <code>.com.gomokumaster.proto.PieceType pieceType = 6;</code>
     */
    public int getPieceTypeValue() {
      return pieceType_;
    }
    /**
     * <code>.com.gomokumaster.proto.PieceType pieceType = 6;</code>
     */
    public Builder setPieceTypeValue(int value) {
      pieceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.PieceType pieceType = 6;</code>
     */
    public com.gomokumaster.proto.PieceType getPieceType() {
      com.gomokumaster.proto.PieceType result = com.gomokumaster.proto.PieceType.valueOf(pieceType_);
      return result == null ? com.gomokumaster.proto.PieceType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.gomokumaster.proto.PieceType pieceType = 6;</code>
     */
    public Builder setPieceType(com.gomokumaster.proto.PieceType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      pieceType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.gomokumaster.proto.PieceType pieceType = 6;</code>
     */
    public Builder clearPieceType() {
      
      pieceType_ = 0;
      onChanged();
      return this;
    }

    private int maxCd_ ;
    /**
     * <code>int32 maxCd = 7;</code>
     */
    public int getMaxCd() {
      return maxCd_;
    }
    /**
     * <code>int32 maxCd = 7;</code>
     */
    public Builder setMaxCd(int value) {
      
      maxCd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 maxCd = 7;</code>
     */
    public Builder clearMaxCd() {
      
      maxCd_ = 0;
      onChanged();
      return this;
    }

    private int color_ ;
    /**
     * <code>int32 color = 8;</code>
     */
    public int getColor() {
      return color_;
    }
    /**
     * <code>int32 color = 8;</code>
     */
    public Builder setColor(int value) {
      
      color_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 color = 8;</code>
     */
    public Builder clearColor() {
      
      color_ = 0;
      onChanged();
      return this;
    }

    private boolean isAlive_ ;
    /**
     * <code>bool isAlive = 9;</code>
     */
    public boolean getIsAlive() {
      return isAlive_;
    }
    /**
     * <code>bool isAlive = 9;</code>
     */
    public Builder setIsAlive(boolean value) {
      
      isAlive_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isAlive = 9;</code>
     */
    public Builder clearIsAlive() {
      
      isAlive_ = false;
      onChanged();
      return this;
    }

    private int skillCd_ ;
    /**
     * <code>int32 skillCd = 11;</code>
     */
    public int getSkillCd() {
      return skillCd_;
    }
    /**
     * <code>int32 skillCd = 11;</code>
     */
    public Builder setSkillCd(int value) {
      
      skillCd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 skillCd = 11;</code>
     */
    public Builder clearSkillCd() {
      
      skillCd_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.gomokumaster.proto.Piece)
  }

  // @@protoc_insertion_point(class_scope:com.gomokumaster.proto.Piece)
  private static final com.gomokumaster.proto.Piece DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gomokumaster.proto.Piece();
  }

  public static com.gomokumaster.proto.Piece getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Piece>
      PARSER = new com.google.protobuf.AbstractParser<Piece>() {
    public Piece parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Piece(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Piece> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Piece> getParserForType() {
    return PARSER;
  }

  public com.gomokumaster.proto.Piece getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

