// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

public interface PieceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gomokumaster.proto.Piece)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int32 x = 2;</code>
   */
  int getX();

  /**
   * <code>int32 y = 3;</code>
   */
  int getY();

  /**
   * <code>string ownerId = 5;</code>
   */
  java.lang.String getOwnerId();
  /**
   * <code>string ownerId = 5;</code>
   */
  com.google.protobuf.ByteString
      getOwnerIdBytes();

  /**
   * <code>.com.gomokumaster.proto.PieceType pieceType = 6;</code>
   */
  int getPieceTypeValue();
  /**
   * <code>.com.gomokumaster.proto.PieceType pieceType = 6;</code>
   */
  com.gomokumaster.proto.PieceType getPieceType();

  /**
   * <code>int32 maxCd = 7;</code>
   */
  int getMaxCd();

  /**
   * <code>int32 color = 8;</code>
   */
  int getColor();

  /**
   * <code>bool isAlive = 9;</code>
   */
  boolean getIsAlive();

  /**
   * <code>int32 skillCd = 11;</code>
   */
  int getSkillCd();
}
