// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

public interface PlayerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gomokumaster.proto.Player)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string avatar = 3;</code>
   */
  java.lang.String getAvatar();
  /**
   * <code>string avatar = 3;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <code>int32 color = 4;</code>
   */
  int getColor();

  /**
   * <pre>
   *剩余的盾棋数
   * </pre>
   *
   * <code>int32 remainingShieldCount = 5;</code>
   */
  int getRemainingShieldCount();

  /**
   * <pre>
   *剩余的弓棋数
   * </pre>
   *
   * <code>int32 remainingArcherCount = 6;</code>
   */
  int getRemainingArcherCount();

  /**
   * <pre>
   *剩余的冲刺棋数
   * </pre>
   *
   * <code>int32 remainingCavalryCount = 7;</code>
   */
  int getRemainingCavalryCount();

  /**
   * <pre>
   *在房间内是否在线
   * </pre>
   *
   * <code>bool isConnected = 8;</code>
   */
  boolean getIsConnected();
}
