// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

/**
 * <pre>
 *用户行为类型枚举
 * </pre>
 *
 * Protobuf enum {@code com.gomokumaster.proto.PlayAction}
 */
public enum PlayAction
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NONE = 0;</code>
   */
  NONE(0),
  /**
   * <code>MOVE = 1;</code>
   */
  MOVE(1),
  /**
   * <code>SKILL = 2;</code>
   */
  SKILL(2),
  /**
   * <code>PLACE = 3;</code>
   */
  PLACE(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NONE = 0;</code>
   */
  public static final int NONE_VALUE = 0;
  /**
   * <code>MOVE = 1;</code>
   */
  public static final int MOVE_VALUE = 1;
  /**
   * <code>SKILL = 2;</code>
   */
  public static final int SKILL_VALUE = 2;
  /**
   * <code>PLACE = 3;</code>
   */
  public static final int PLACE_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PlayAction valueOf(int value) {
    return forNumber(value);
  }

  public static PlayAction forNumber(int value) {
    switch (value) {
      case 0: return NONE;
      case 1: return MOVE;
      case 2: return SKILL;
      case 3: return PLACE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PlayAction>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PlayAction> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PlayAction>() {
          public PlayAction findValueByNumber(int number) {
            return PlayAction.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.gomokumaster.proto.GameMsgProtocol.getDescriptor().getEnumTypes().get(1);
  }

  private static final PlayAction[] VALUES = values();

  public static PlayAction valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PlayAction(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.gomokumaster.proto.PlayAction)
}

