// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/game.proto

package com.gomokumaster.proto;

/**
 * Protobuf type {@code com.gomokumaster.proto.Player}
 */
public  final class Player extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gomokumaster.proto.Player)
    PlayerOrBuilder {
  // Use Player.newBuilder() to construct.
  private Player(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Player() {
    id_ = "";
    name_ = "";
    avatar_ = "";
    color_ = 0;
    remainingShieldCount_ = 0;
    remainingArcherCount_ = 0;
    remainingCavalryCount_ = 0;
    isConnected_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Player(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            avatar_ = s;
            break;
          }
          case 32: {

            color_ = input.readInt32();
            break;
          }
          case 40: {

            remainingShieldCount_ = input.readInt32();
            break;
          }
          case 48: {

            remainingArcherCount_ = input.readInt32();
            break;
          }
          case 56: {

            remainingCavalryCount_ = input.readInt32();
            break;
          }
          case 64: {

            isConnected_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_Player_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_Player_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gomokumaster.proto.Player.class, com.gomokumaster.proto.Player.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVATAR_FIELD_NUMBER = 3;
  private volatile java.lang.Object avatar_;
  /**
   * <code>string avatar = 3;</code>
   */
  public java.lang.String getAvatar() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      avatar_ = s;
      return s;
    }
  }
  /**
   * <code>string avatar = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAvatarBytes() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      avatar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLOR_FIELD_NUMBER = 4;
  private int color_;
  /**
   * <code>int32 color = 4;</code>
   */
  public int getColor() {
    return color_;
  }

  public static final int REMAININGSHIELDCOUNT_FIELD_NUMBER = 5;
  private int remainingShieldCount_;
  /**
   * <pre>
   *剩余的盾棋数
   * </pre>
   *
   * <code>int32 remainingShieldCount = 5;</code>
   */
  public int getRemainingShieldCount() {
    return remainingShieldCount_;
  }

  public static final int REMAININGARCHERCOUNT_FIELD_NUMBER = 6;
  private int remainingArcherCount_;
  /**
   * <pre>
   *剩余的弓棋数
   * </pre>
   *
   * <code>int32 remainingArcherCount = 6;</code>
   */
  public int getRemainingArcherCount() {
    return remainingArcherCount_;
  }

  public static final int REMAININGCAVALRYCOUNT_FIELD_NUMBER = 7;
  private int remainingCavalryCount_;
  /**
   * <pre>
   *剩余的冲刺棋数
   * </pre>
   *
   * <code>int32 remainingCavalryCount = 7;</code>
   */
  public int getRemainingCavalryCount() {
    return remainingCavalryCount_;
  }

  public static final int ISCONNECTED_FIELD_NUMBER = 8;
  private boolean isConnected_;
  /**
   * <pre>
   *在房间内是否在线
   * </pre>
   *
   * <code>bool isConnected = 8;</code>
   */
  public boolean getIsConnected() {
    return isConnected_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getAvatarBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, avatar_);
    }
    if (color_ != 0) {
      output.writeInt32(4, color_);
    }
    if (remainingShieldCount_ != 0) {
      output.writeInt32(5, remainingShieldCount_);
    }
    if (remainingArcherCount_ != 0) {
      output.writeInt32(6, remainingArcherCount_);
    }
    if (remainingCavalryCount_ != 0) {
      output.writeInt32(7, remainingCavalryCount_);
    }
    if (isConnected_ != false) {
      output.writeBool(8, isConnected_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getAvatarBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, avatar_);
    }
    if (color_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, color_);
    }
    if (remainingShieldCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, remainingShieldCount_);
    }
    if (remainingArcherCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, remainingArcherCount_);
    }
    if (remainingCavalryCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, remainingCavalryCount_);
    }
    if (isConnected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isConnected_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gomokumaster.proto.Player)) {
      return super.equals(obj);
    }
    com.gomokumaster.proto.Player other = (com.gomokumaster.proto.Player) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && getAvatar()
        .equals(other.getAvatar());
    result = result && (getColor()
        == other.getColor());
    result = result && (getRemainingShieldCount()
        == other.getRemainingShieldCount());
    result = result && (getRemainingArcherCount()
        == other.getRemainingArcherCount());
    result = result && (getRemainingCavalryCount()
        == other.getRemainingCavalryCount());
    result = result && (getIsConnected()
        == other.getIsConnected());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + AVATAR_FIELD_NUMBER;
    hash = (53 * hash) + getAvatar().hashCode();
    hash = (37 * hash) + COLOR_FIELD_NUMBER;
    hash = (53 * hash) + getColor();
    hash = (37 * hash) + REMAININGSHIELDCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getRemainingShieldCount();
    hash = (37 * hash) + REMAININGARCHERCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getRemainingArcherCount();
    hash = (37 * hash) + REMAININGCAVALRYCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getRemainingCavalryCount();
    hash = (37 * hash) + ISCONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsConnected());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gomokumaster.proto.Player parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gomokumaster.proto.Player parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gomokumaster.proto.Player parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gomokumaster.proto.Player parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gomokumaster.proto.Player parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.Player parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gomokumaster.proto.Player parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.Player parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gomokumaster.proto.Player parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gomokumaster.proto.Player parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gomokumaster.proto.Player prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gomokumaster.proto.Player}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gomokumaster.proto.Player)
      com.gomokumaster.proto.PlayerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_Player_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_Player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gomokumaster.proto.Player.class, com.gomokumaster.proto.Player.Builder.class);
    }

    // Construct using com.gomokumaster.proto.Player.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";

      avatar_ = "";

      color_ = 0;

      remainingShieldCount_ = 0;

      remainingArcherCount_ = 0;

      remainingCavalryCount_ = 0;

      isConnected_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gomokumaster.proto.GameMsgProtocol.internal_static_com_gomokumaster_proto_Player_descriptor;
    }

    public com.gomokumaster.proto.Player getDefaultInstanceForType() {
      return com.gomokumaster.proto.Player.getDefaultInstance();
    }

    public com.gomokumaster.proto.Player build() {
      com.gomokumaster.proto.Player result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.gomokumaster.proto.Player buildPartial() {
      com.gomokumaster.proto.Player result = new com.gomokumaster.proto.Player(this);
      result.id_ = id_;
      result.name_ = name_;
      result.avatar_ = avatar_;
      result.color_ = color_;
      result.remainingShieldCount_ = remainingShieldCount_;
      result.remainingArcherCount_ = remainingArcherCount_;
      result.remainingCavalryCount_ = remainingCavalryCount_;
      result.isConnected_ = isConnected_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gomokumaster.proto.Player) {
        return mergeFrom((com.gomokumaster.proto.Player)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gomokumaster.proto.Player other) {
      if (other == com.gomokumaster.proto.Player.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getAvatar().isEmpty()) {
        avatar_ = other.avatar_;
        onChanged();
      }
      if (other.getColor() != 0) {
        setColor(other.getColor());
      }
      if (other.getRemainingShieldCount() != 0) {
        setRemainingShieldCount(other.getRemainingShieldCount());
      }
      if (other.getRemainingArcherCount() != 0) {
        setRemainingArcherCount(other.getRemainingArcherCount());
      }
      if (other.getRemainingCavalryCount() != 0) {
        setRemainingCavalryCount(other.getRemainingCavalryCount());
      }
      if (other.getIsConnected() != false) {
        setIsConnected(other.getIsConnected());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gomokumaster.proto.Player parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gomokumaster.proto.Player) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object avatar_ = "";
    /**
     * <code>string avatar = 3;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string avatar = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string avatar = 3;</code>
     */
    public Builder setAvatar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      avatar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string avatar = 3;</code>
     */
    public Builder clearAvatar() {
      
      avatar_ = getDefaultInstance().getAvatar();
      onChanged();
      return this;
    }
    /**
     * <code>string avatar = 3;</code>
     */
    public Builder setAvatarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      avatar_ = value;
      onChanged();
      return this;
    }

    private int color_ ;
    /**
     * <code>int32 color = 4;</code>
     */
    public int getColor() {
      return color_;
    }
    /**
     * <code>int32 color = 4;</code>
     */
    public Builder setColor(int value) {
      
      color_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 color = 4;</code>
     */
    public Builder clearColor() {
      
      color_ = 0;
      onChanged();
      return this;
    }

    private int remainingShieldCount_ ;
    /**
     * <pre>
     *剩余的盾棋数
     * </pre>
     *
     * <code>int32 remainingShieldCount = 5;</code>
     */
    public int getRemainingShieldCount() {
      return remainingShieldCount_;
    }
    /**
     * <pre>
     *剩余的盾棋数
     * </pre>
     *
     * <code>int32 remainingShieldCount = 5;</code>
     */
    public Builder setRemainingShieldCount(int value) {
      
      remainingShieldCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *剩余的盾棋数
     * </pre>
     *
     * <code>int32 remainingShieldCount = 5;</code>
     */
    public Builder clearRemainingShieldCount() {
      
      remainingShieldCount_ = 0;
      onChanged();
      return this;
    }

    private int remainingArcherCount_ ;
    /**
     * <pre>
     *剩余的弓棋数
     * </pre>
     *
     * <code>int32 remainingArcherCount = 6;</code>
     */
    public int getRemainingArcherCount() {
      return remainingArcherCount_;
    }
    /**
     * <pre>
     *剩余的弓棋数
     * </pre>
     *
     * <code>int32 remainingArcherCount = 6;</code>
     */
    public Builder setRemainingArcherCount(int value) {
      
      remainingArcherCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *剩余的弓棋数
     * </pre>
     *
     * <code>int32 remainingArcherCount = 6;</code>
     */
    public Builder clearRemainingArcherCount() {
      
      remainingArcherCount_ = 0;
      onChanged();
      return this;
    }

    private int remainingCavalryCount_ ;
    /**
     * <pre>
     *剩余的冲刺棋数
     * </pre>
     *
     * <code>int32 remainingCavalryCount = 7;</code>
     */
    public int getRemainingCavalryCount() {
      return remainingCavalryCount_;
    }
    /**
     * <pre>
     *剩余的冲刺棋数
     * </pre>
     *
     * <code>int32 remainingCavalryCount = 7;</code>
     */
    public Builder setRemainingCavalryCount(int value) {
      
      remainingCavalryCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *剩余的冲刺棋数
     * </pre>
     *
     * <code>int32 remainingCavalryCount = 7;</code>
     */
    public Builder clearRemainingCavalryCount() {
      
      remainingCavalryCount_ = 0;
      onChanged();
      return this;
    }

    private boolean isConnected_ ;
    /**
     * <pre>
     *在房间内是否在线
     * </pre>
     *
     * <code>bool isConnected = 8;</code>
     */
    public boolean getIsConnected() {
      return isConnected_;
    }
    /**
     * <pre>
     *在房间内是否在线
     * </pre>
     *
     * <code>bool isConnected = 8;</code>
     */
    public Builder setIsConnected(boolean value) {
      
      isConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *在房间内是否在线
     * </pre>
     *
     * <code>bool isConnected = 8;</code>
     */
    public Builder clearIsConnected() {
      
      isConnected_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.gomokumaster.proto.Player)
  }

  // @@protoc_insertion_point(class_scope:com.gomokumaster.proto.Player)
  private static final com.gomokumaster.proto.Player DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gomokumaster.proto.Player();
  }

  public static com.gomokumaster.proto.Player getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Player>
      PARSER = new com.google.protobuf.AbstractParser<Player>() {
    public Player parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Player(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Player> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Player> getParserForType() {
    return PARSER;
  }

  public com.gomokumaster.proto.Player getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

